### ISSUE TITLE
Update Cassandra based global variables in values.yaml.

### ISSUE THREAD

**Issue by tsaxena18** [TIBCOSoftware/be-tools#100]
The values.yaml file under helm contains separate global variables for Cassandra host and port while the Cassandra connection section in CDD does not have separate fields for host and port. There is a single field for server contact which is made up of hostname and port as hostname:port (default value --> localhost:9042).
So update the yaml file accordingly.

**Comment by nareshkumarthota** [comment]
fix is available in branch `chore-issue-fixes`. kindly confirm the same will create a PR.

**Comment by tsaxena18** [comment]
Verified the Store use case with Cassandra for updated variables in values.yaml file and it went fine.
Attached log for the reference.
[log.txt](https://github.com/TIBCOSoftware/be-tools/files/5163250/log.txt)
