### ISSUE TITLE
Helm deployment fails for persistence option Shared Nothing with OpenShift platform.

### ISSUE THREAD

**Issue by tsaxena18** [TIBCOSoftware/be-tools#101]
Use case --> FTL+Ignite+SharedNothing for OpenShift.
$ helm install fdsn600app ./helm --set cpType=openshift
Error: YAML parse error on BE Helm Chart/templates/persistent-volume-and-claim.yaml: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal array into Go value of type releaseutil.SimpleHead

With dry-run, found detailed error trace as described below -->
$ helm install fdsn600app . --debug --dry-run
install.go:159: [debug] Original chart version: ""
install.go:176: [debug] CHART PATH: /home/apps/be-tools/cloud/kubernetes/helm

Error: YAML parse error on BE Helm Chart/templates/persistent-volume-and-claim.yaml: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal array into Go value of type releaseutil.SimpleHead
helm.go:84: [debug] error unmarshaling JSON: while decoding JSON: json: cannot unmarshal array into Go value of type releaseutil.SimpleHead
YAML parse error on BE Helm Chart/templates/persistent-volume-and-claim.yaml
helm.sh/helm/v3/pkg/releaseutil.(*manifestFile).sort
        /home/circleci/helm.sh/helm/pkg/releaseutil/manifest_sorter.go:146
helm.sh/helm/v3/pkg/releaseutil.SortManifests
        /home/circleci/helm.sh/helm/pkg/releaseutil/manifest_sorter.go:106
helm.sh/helm/v3/pkg/action.(*Configuration).renderResources
        /home/circleci/helm.sh/helm/pkg/action/action.go:159
helm.sh/helm/v3/pkg/action.(*Install).Run
        /home/circleci/helm.sh/helm/pkg/action/install.go:238
main.runInstall
        /home/circleci/helm.sh/helm/cmd/helm/install.go:229
main.newInstallCmd.func1
        /home/circleci/helm.sh/helm/cmd/helm/install.go:117
github.com/spf13/cobra.(*Command).execute
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842
github.com/spf13/cobra.(*Command).ExecuteC
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950
github.com/spf13/cobra.(*Command).Execute
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main
        /home/circleci/helm.sh/helm/cmd/helm/helm.go:83
runtime.main
        /usr/local/go/src/runtime/proc.go:203
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1357

**Comment by nareshkumarthota** [comment]
typo err in template file. Fix is moved to branch `fix-issue-101` kindly confirm once.

**Comment by tsaxena18** [comment]
Updating persistent-volume-and-claim.yaml under templates folder for extra "-" resolved the initial issue.
But now I am facing issue with persistence volume not getting bound. The volume and mount templates are not created properly. In the generated yaml, persistence volume claim is missing storage class name. 
 volumeMounts:
          - mountPath: /mnt/tibco/be/data-store
            name: store
  volumeClaimTemplates:
    - metadata:
        name: store
      spec:
        accessModes: [ReadWriteOnce]
        volumeName: pv0003
        resources:
          requests:
            storage: 0.5Gi

**Comment by nareshkumarthota** [comment]
fix is available in branch `chore-issue-fixes`. kindly confirm the same will create a PR.

**Comment by tsaxena18** [comment]
Verified the Shared Nothing use case with FTL and AS as cluster provider and it went fine for both the cases.
Attached log for the reference.
[sn.zip](https://github.com/TIBCOSoftware/be-tools/files/5163262/sn.zip)

**Comment by rameshpolishetti** [comment]
@tsaxena18 fix is merged into master. Please close it from your end.

**Comment by tsaxena18** [comment]
Closing as use case is working fine for both AS2x and FTL.
