### ISSUE TITLE
Unix version: BE hotfix not installed (zip file added install files folder)

### ISSUE THREAD

**Issue by staffwaremueller** [TIBCOSoftware/be-tools#102]
Hotfix not installed caused by a script issue when check for BE hotfix file. The filename (hotfix) does not include the ARG_EDITION (enterprise).

Filename: TIB_businessevents-hf_5.6.1_HF-004_linux26gl25_x86_64.zip

Script: s2i/create_builder_image.sh
Variable beHfCntd set to 0 (filename used for the check not match the real name)

BE_HF_REGEX="${BE_PRODUCT}-${ARG_EDITION}_*_HF"
...
beHfPckgs=$(find $ARG_INSTALLER_LOCATION -name "$BE_HF_REGEX*$INSTALLER_PLATFORM")
beHfCnt=$(find $ARG_INSTALLER_LOCATION -name  "$BE_HF_REGEX*$INSTALLER_PLATFORM" | wc -l)

Note:
Hotfix still not installed correctly when set BE_HF_REGEX="${BE_PRODUCT}-*_HF" (TIBCOUniversal installer binary not found).

**Woraround**:
Add hotfix (zip file) to the root folder of the BE 5.x base installation. The TIBCO Universal Installer unzip that file and installs the hotfix with the base version.
Steps:
- Copy BE installer and hotfix to the Unix system (e.g. /home/tibco/work/installerFiles)
- Create tmp folder (e.g. /home/tibco/work/installerFiles)
- Unzip base version in that folder
  e.g.
  cd /home/tibco/work/installerFiles/tmp
  unzip ../TIB_businessevents-enterprise_5.6.1_linux26gl25_x86_64.zip

- Move hotfix to tmp folder
  e.g.
  mv ../TIB_businessevents-hf_5.6.1_HF-004_linux26gl25_x86_64.zip .
 
- Create new zip file (same name as base version)
  e.g.
  zip -r TIB_businessevents-enterprise_5.6.1_linux26gl25_x86_64.zip *
 
- Copy the new created zip file to your docker installfiles folder and create the image
  ./build_app_image.sh -l _installerFiles_ -a _appFiles_ -r _imagename_ -d _dockerfile_

**Comment by CloudDevBe** [comment]
@staffwaremueller Variable beHfCnt is properly set to 1.
To check, I added echo beHfPckgs : $beHfPckgs and echo beHfCnt : $beHfCnt in s2i/create_builder_image.sh

Following are the logs:
./build_app_image.sh -l /Users/shrikant/Downloads/installationzipfiles/5.61 -a /Users/shrikant/Downloads/Installationfiles/fd -r fdhf:01
beHfPckgs : /Users/shrikant/Downloads/installationzipfiles/5.61/TIB_businessevents-hf_5.6.1_HF-004_linux26gl25_x86_64.zip
beHfCnt : 1
INFO:Supplied Arguments :
----------------------------------------------
INFO:VERSION : 5.6.1
INFO:EDITION : enterprise
INFO:INSTALLER DIRECTORY : /Users/shrikant/Downloads/installationzipfiles/5.61
INFO:APPLICATION DATA DIRECTORY : /Users/shrikant/Downloads/Installationfiles/fd
INFO:ADDONS : na
INFO:DOCKERFILE : Dockerfile
INFO:BE-HF : 004
INFO:AS Legacy-HF : na
INFO:IMAGE VERSION : fdhf:01


Are you trying with the latest code?

**Comment by staffwaremueller** [comment]
Thanks, you right I loaded an old version. I used the link referenced in the manual of BE version 5.6.1 and that link points to first version of the scripts and not to top folder.

See:
https://docs.tibco.com/pub/businessevents-enterprise/5.6.1/doc/html/GUID-6363E425-C15D-4FB7-BE41-5BC83A1B9971.html

Link:
TIBCO BusinessEvents GitHub repository points to:
  https://github.com/TIBCOSoftware/be-tools/tree/v1.0
  
Correct link:
https://github.com/TIBCOSoftware/be-tools

The latest version works. You can close that issue (link is correct in BE 6.0.0 manual).
https://docs.tibco.com/pub/businessevents-enterprise/6.0.0/doc/html/Default.htm#_templates/Before-you-begin.htm?Highlight=docker
