### ISSUE TITLE
PKS-GCP getting error while pulling image from private registry when helm is used for deployment

### ISSUE THREAD

**Issue by jgirase-tibco** [TIBCOSoftware/be-tools#103]
For the application deployment on kubernetes cluster with vendor PKS-GCP , it show error as "ImagePullBackOff" when private registry like google container registry is used for docker images.
Followed the steps from below page to configure service account but it does not work ,
https://github.com/TIBCOSoftware/be-tools/wiki/Setting%20up%20Google%20Container%20Registry

If google container registry is marked as public repo then it works fine.

Error:

Events:
  Type     Reason     Age                From                                              Message
  ----     ------     ----               ----                                              -------
  Normal   Scheduled  44s                default-scheduler                                 Successfully assigned default/fdcache-test-becacheagent-0 to vm-8c8595a0-e04c-4280-7ee3-d583ebb8ae3c
  Normal   BackOff    19s (x2 over 42s)  kubelet, vm-8c8595a0-e04c-4280-7ee3-d583ebb8ae3c  Back-off pulling image "us.gcr.io/streambase-200318/fdcache:6.0"
  Warning  Failed     19s (x2 over 42s)  kubelet, vm-8c8595a0-e04c-4280-7ee3-d583ebb8ae3c  Error: ImagePullBackOff
  Normal   Pulling    5s (x3 over 43s)   kubelet, vm-8c8595a0-e04c-4280-7ee3-d583ebb8ae3c  Pulling image "us.gcr.io/streambase-200318/fdcache:6.0"
  Warning  Failed     5s (x3 over 43s)   kubelet, vm-8c8595a0-e04c-4280-7ee3-d583ebb8ae3c  Failed to pull image "us.gcr.io/streambase-200318/fdcache:6.0": rpc error: code = Unknown desc = Error response from daemon: pull access denied for us.gcr.io/streambase-200318/fdcache, repository does not exist or may require 'docker login': denied: Permission denied for "6.0" from request "/v2/streambase-200318/fdcache/manifests/6.0".
  Warning  Failed     5s (x3 over 43s)   kubelet, vm-8c8595a0-e04c-4280-7ee3-d583ebb8ae3c  Error: ErrImagePull

**Comment by nareshkumarthota** [comment]
fix is available in branch `fix-issue-103` kindly confirm.

imagepullsecret name option is given along with image credentials. If image pull secret name field is supplied in `values.yaml` image credentials section is ignored.

**Comment by jgirase-tibco** [comment]
Its working after specifying pullsecret value for field imagepullsecret: in values.yaml for helm.
