### ISSUE TITLE
Unit Tests for Docker and Helm

### ISSUE THREAD

**Issue by vpatil-tibco** [TIBCOSoftware/be-tools#106]
Things to cover here,
1. Enhance/add more docker tests.
2. Add unit tests for Helm.
3. Plug unit tests with travis.

**Comment by LakshmiMekala** [comment]
Please find tasks status below:

Helm Template tests -completed
Travis-CI integration - completed
Plug unit test with travis-completed

**Comment by LakshmiMekala** [comment]
Implentation done. PR #126
