### ISSUE TITLE
Update usage file under s2i.

### ISSUE THREAD

**Issue by tsaxena18** [TIBCOSoftware/be-tools#108]
The section has not been updated with the new changes.
The current text describes the command usage as :
./create_builder_image.sh -l <installers-location> -v <BE-version> -i <image-version>
where
[-l|--installers-location]  :       Location where TIBCO BusinessEvents and other required installers are located [required]
[-d|--docker-file]          :       Dockerfile to be used for generating image.(default Dockerfile) [optional]"
For example:
./create_builder_image.sh -l /Users/test/BE_Installers

But currently it is :
[apps@beqacentos7 s2i]$ ./create_builder_image.sh -h

Usage: create_builder_image.sh

 [-l|--installers-location]  :       Location where TIBCO BusinessEvents and other required installers are located [required]

 [-d|--docker-file]          :       Dockerfile to be used for generating image.(default Dockerfile) [optional]

 [--disable-tests]           :       Disables docker unit tests on created image. [optional]

 [--gv-providers]            :       Names of GV providers to be included in the image. Supported value(s) - consul [optional]

 [-r|--repo]                 :       The builder image Repository (example - s2ibuilder:latest) [required]

 [-h|--help]                 :       Print the usage of script [optional]

 NOTE : supply long options with '='

**Comment by nareshkumarthota** [comment]
updated the required changes in branch ` fix-issue-108`. kindly confirm the same.

**Comment by tsaxena18** [comment]
Checked from fix-issue-108 branch , the documentation part has been updated correctly.
