### ISSUE TITLE
Correct the helm deployment output.

### ISSUE THREAD

**Issue by tsaxena18** [TIBCOSoftware/be-tools#109]
With the configurations set in values.yaml for cluster provider, cache provider, store, etc. we do helm deployment and get the last statement of output as :
Your release is named fdsa600app. and deployed in `openshift` with `FTL` mode.

FTL is a cluster provider and when we talk about mode in context with BE its usually a persistence or OM options. 
So if my setup is OpenShift as cloud platform, FTL as cluster provider and Store as OM then the statement should come as :
Your release is named fdsa600app. and deployed in `OpenShift` with `FTL` as cluster provider and mode as 'Store'.

**Comment by tsaxena18** [comment]
1. For all the AS2x clustered cases we get,
Your release is named fdc600app. and deployed in `azure` with `AS2` mode 

2. For all the FTL clustered cases we get,
Your release is named fdc600app. and deployed in `azure` with `FTL` mode

3. For unclustered case we get,
Your release is named fd600app. and deployed in `azure` with `unclustered` mode

So there are only 3 types of output. Now change should be to also include the mode as None, Store, etc.

**Comment by nareshkumarthota** [comment]
The notes text can be modified like below mentioned. I think this serves the purpose.
Your release is named {{ .Release.Name }}. and deployed in `{{.Values.cpType}}`. Cluster Type: `{{.Values.cmType}}`. OM Type: `{{.Values.omType}}`.
