### ISSUE TITLE
Builder script to run on windows.

### ISSUE THREAD

**Issue by tsaxena18** [TIBCOSoftware/be-tools#11]
S2I toolkit is also available for windows and we also support creating images for Linux container from windows. So a similar script should be available to use on windows to be in sync with our existing docker folders.

**Comment by tsaxena18** [comment]
Tried to build application image for linux container on windows by running create_builder_image.bat and then s2i utility and it went fine.

**Comment by LakshmiMekala** [comment]
Closing issue as per above comments
