### ISSUE TITLE
Adding application monitoring to Helm

### ISSUE THREAD

**Issue by vpatil-tibco** [TIBCOSoftware/be-tools#116]
BE currently supports application monitoring.
1. InfluxDB with Dashboards done in Grafana or any other InfluxDB support Dashboarding tool.
2. Tibco Streaming with Dashboards done in Tibco LiveViewWeb.

The scope of this issue,
1. Configurative support for application metrics. This depends on the cdd configuration.
2. Client connection support i.e. cdd configs for InfluxDB and Tibco Streaming to be exposed via values.yml
3. InfluxDB+Grafana and TIBCO Streaming+LiveViewWeb in a production setup will most likely will always be managed/deployed externally/separately. However its good to have an oob support for these, specifically the ones which have public charts already available like InfluxDB, Grafana.

**Comment by LakshmiMekala** [comment]
Included application monitoring to helm for below points:
1. InfluxDB with Dashboards done in Grafana or any other InfluxDB support Dashboarding tool.(Added dependency charts for InfluxDB and Grafana)
2. Tibco Streaming with Dashboards done in Tibco LiveViewWeb.

Code changes are available [feature-app-metrics](https://github.com/TIBCOSoftware/be-tools/tree/feature-app-metrics)

**Comment by LakshmiMekala** [comment]
Added option for custom metrics support
