### ISSUE TITLE
Performance improvements for docker

### ISSUE THREAD

**Issue by vpatil-tibco** [TIBCOSoftware/be-tools#117]
Currently our docker images have roughly 40+ steps, these translate to individual layers. More the layers, more is the time it takes to build an image plus add to the overall size.

Goal of this issue to evaluate ways to reduce the number of steps involved. Few things to check,
1. Redundant steps, if any can be removed are not needed.
2. Can certain steps be clubbed together.

**Comment by nareshkumarthota** [comment]
scripts improved and made available in branch `docker-scripts-improvements`

**Comment by ykalidin** [comment]
Docker image creation steps and layers in docker image are reduced.Verified in docker-scripts-improvements.

**Comment by tsaxena18** [comment]
There are less steps now while creating docker images. It is taking roughly 23 steps for app and 21 steps for RMS with less time as before. 

[apps@beqacentos7 docker]$ ./build_image.sh -i app -a /home/apps/Testing/temp610/None-Iginte -s /home/apps/Installers/BE/610 -t fdci:610 --disable-tests
INFO: Supplied/Derived Data:

INFO: INSTALLER DIRECTORY          : [/home/apps/Installers/BE/610]
INFO: APPLICATION DATA DIRECTORY   : [/home/apps/Testing/temp610/None-Iginte]
INFO: BE VERSION                   : [6.1.0]
INFO: BE ADDONS                    : [process]
INFO: AS LEGACY VERSION            : [2.4.1]
INFO: FTL VERSION                  : [6.5.0]
INFO: AS VERSION                   : [4.5.0]
INFO: CDD FILE NAME                : [IgniteClusterDeploy.cdd]
INFO: EAR FILE NAME                : [fdcache.ear]
INFO: DOCKERFILE                   : [./dockerfiles/Dockerfile]
INFO: IMAGE TAG                    : [fdci:610]
INFO: JRE VERSION                  : [11]

WARN: The directory: [/home/apps/Installers/BE/610] contains both FTL and Activespaces(legacy) installers. Removing unused installer improves the docker image size.

INFO: Copying package: [/home/apps/Installers/BE/610/TIB_businessevents-enterprise_6.1.0_linux26gl25_x86_64.zip]
INFO: Copying package: [/home/apps/Installers/BE/610/TIB_activespaces_2.4.1_linux_x86_64.zip]
INFO: Copying package: [/home/apps/Installers/BE/610/TIB_businessevents-process_6.1.0_linux26gl25_x86_64.zip]
INFO: Copying package: [/home/apps/Installers/BE/610/TIB_ftl_6.5.0_linux_x86_64.zip]
INFO: Copying package: [/home/apps/Installers/BE/610/TIB_as_4.5.0_linux_x86_64.zip]

INFO: Building docker image.


[+] Building 475.8s (23/23) FINISHED
 => [internal] load build definition from Dockerfile                                                                                                                                    0.4s
 => => transferring dockerfile: 4.01kB                                                                                                                                                  0.0s
 => [internal] load .dockerignore                                                                                                                                                       0.5s
 => => transferring context: 2B                                                                                                                                                         0.0s
 => [internal] load metadata for docker.io/library/ubuntu:20.10                                                                                                                         0.0s
 => CACHED [stage-1 1/6] FROM docker.io/library/ubuntu:20.10                                                                                                                            0.0s
 => [internal] load build context                                                                                                                                                      40.3s
 => => transferring context: 2.39GB                                                                                                                                                    25.7s
 => [intermediate 2/13] RUN apt-get update  && apt-get install -y unzip procps findutils                                                                                               68.6s
 => [intermediate 3/13] COPY lib/*.pm lib/*.py lib/*.sh installers/* lib/run /home/tibco/be/                                                                                           33.3s
 => [intermediate 4/13] COPY gvproviders /home/tibco/be/gvproviders                                                                                                                     0.4s
 => [intermediate 5/13] COPY app/* /opt/tibco/be/ext/                                                                                                                                   0.4s
 => [intermediate 6/13] WORKDIR /home/tibco/be                                                                                                                                          0.5s
 => [intermediate 7/13] RUN chmod +x *.sh *.pm                                                                                                                                          1.0s
 => [intermediate 8/13] RUN perl -I. -Mbe_docker_install -e "be_docker_install::install_ftl('6.5.0','na')"                                                                             29.8s
 => [intermediate 9/13] RUN perl -I. -Mbe_docker_install -e "be_docker_install::install_activespaces('4.5.0','na')"                                                                    15.3s
 => [intermediate 10/13] RUN perl -I. -Mbe_docker_install -e "be_docker_install::install_be('6.1.0','enterprise','process','na','na','2.4.1')"                                        286.0s
 => [intermediate 11/13] RUN perl -I. -Mbe_docker_install -e "be_docker_install::replaceRunbeVersionToken('6.1.0','./run')"                                                             1.2s
 => [intermediate 12/13] RUN perl -I. -Mbe_docker_install -e "be_docker_install::generateAnnotationIndexes('/opt/tibco/be/6.1', '/opt/tibco/tibcojre64/11')"  && rm -rf as_installers  11.0s
 => [intermediate 13/13] RUN ./prepare_finalimage.sh                                                                                                                                   17.7s
 => CACHED [stage-1 2/6] COPY --from=intermediate /home/tibco/be /home/tibco/be                                                                                                         0.0s
 => CACHED [stage-1 3/6] COPY --from=intermediate /tibco_home /opt/tibco                                                                                                                0.0s
 => CACHED [stage-1 4/6] RUN chmod +x /home/tibco/be/gvproviders/*.sh && /home/tibco/be/gvproviders/setup.sh na                                                                         0.0s
 => CACHED [stage-1 5/6] RUN mkdir -p /mnt/tibco/be/logs  && mkdir -p /mnt/tibco/be/data-store                                                                                          0.0s
 => CACHED [stage-1 6/6] WORKDIR /home/tibco/be                                                                                                                                         0.0s
 => exporting to image                                                                                                                                                                  0.4s
 => => exporting layers                                                                                                                                                                 0.0s
 => => writing image sha256:fc98952b3fdc129a9980528997b6fa789c5dc3e6007176a2dbd27e81156b0b46                                                                                            0.0s
 => => naming to docker.io/library/fdci:610                                                                                                                                             0.0s
Deleted build cache objects:
onxsj5crmkj1nmz6cm5sdne04
2x80amaztaf2voqg801rbtvrb
ks5w52r09bwmu1tmtr22v2cpb
57n4jbkaaup95wfcn6dzoj2ph
e5k67ta6qpmyx0qcy1vvjtig6
e4myc91ursgfmoo1pv5ndh0zr
w9bn9blrdlozr6pu380wmso58
8hethyig25hcpfk7qevzkttwd
mkc6lwa50nsoa4e54rfcz02cm
xlaihx4tydt3cesgcji2rg9hh
tcsfu8mbn57y1aouwntnt1chs
j2pexefbrx7au8qmg1u8xyyis
duap91u3gdefti0hhi34ukuls
rjmcabjfcudyxt01cky9az2gl
tg4a5vkb6kowv4g8j0xbtrq0y

Total reclaimed space: 8.808GB
INFO: Deleting folder: [tmp_23221].
INFO: Docker build successful. Image Name: [fdci:610]

**Comment by rameshpolishetti** [comment]
Closing the issue as it is verified successfully.
