### ISSUE TITLE
Update individual page wiki links to appropriate sections

### ISSUE THREAD

**Issue by vpatil-tibco** [TIBCOSoftware/be-tools#118]
Today all wiki reference take user to the base wiki link i.e. - https://github.com/TIBCOSoftware/be-tools/wiki

Rather we should point users to appropriate sections within the wiki link. So on the Helm page link should take users directly to https://github.com/TIBCOSoftware/be-tools/wiki/Helm%20Chart

Or docker should take them to https://github.com/TIBCOSoftware/be-tools/wiki/Dockerize%20TIBCO%20BusinessEvents

**Comment by LakshmiMekala** [comment]
Fixed with PR #125
