### ISSUE TITLE
Update product name in run_tests.sh usage description. 

### ISSUE THREAD

**Issue by tsaxena18** [TIBCOSoftware/be-tools#119]
$ ./run_tests.sh -h

Usage: run_tests.sh

 [ -i|--image-name]           : **Be** app image name with tag <image-name>:<tag> ex(be6:v1) [required]

 [ -b|--be-version]           : **Be** version in x.x format ex(5.6) [required]

 [ -c|--cdd-filename]         : CDD file name ex(fd.cdd) [required]

 [ -e|--ear-filename]         : EAR file name ex(fd.ear) [required]

 [-al|--as-legacy-version]    : **Activespaces** legacy version in x.x format ex(2.4) [optional]

 [-as|--as-version]           : **Activespaces** version in x.x format ex(4.4) [optional]

 [ -f|--ftl-version]          : **Ftl** version in x.x format ex(6.4) [optional]

 [-kv|--key-value-pair]       : Key value pairs to replace in yaml files ex(JRE_VERSION=11) can be multiple [optional]

 [ -h|--help]                 : Print the usage of script [optional]

 NOTE : supply long options with '='

Update highlighted name as BE, ActiveSpaces, FTL.

**Comment by LakshmiMekala** [comment]
Fixed in branch [fix-dockertest-issues](https://github.com/TIBCOSoftware/be-tools/tree/fix-dockertest-issues)

**Comment by tsaxena18** [comment]
Confirmed, the usage is fine now with products name.
 [apps@beqacentos7 tests]$ sh run_tests.sh -h

Usage: run_tests.sh

 [ -i|--image-name]           : BE app image name with tag <image-name>:<tag> ex(be6:v1) [required]

 [ -b|--be-version]           : BE version in x.x format ex(5.6) [required]

 [-al|--as-legacy-version]    : AS legacy version in x.x format ex(2.4) [optional]

 [-as|--as-version]           : ACTIVESPACES version in x.x format ex(4.4) [optional]

 [ -f|--ftl-version]          : FTL version in x.x format ex(6.4) [optional]

 [-kv|--key-value-pair]       : Key value pairs to replace in yaml files ex(JRE_VERSION=11) can be multiple [optional]

 [ -h|--help]                 : Print the usage of script [optional]

 NOTE : supply long options with '='
