### ISSUE TITLE
Avoid extra message in case of failure in run_tests.sh

### ISSUE THREAD

**Issue by tsaxena18** [TIBCOSoftware/be-tools#120]
1. When all tests passed.
=================================
============ RESULTS ============
=================================
Passes:      17
Failures:    0
Duration:    9.974871635s
Total tests: 17

PASS

=================END OF CONTAINER STRUCTURE TESTS==================

2. When few tests failed.
=================================
============ RESULTS ============
=================================
Passes:      14
Failures:    3
Duration:    3.292454662s
Total tests: 17

FAIL
**time="2020-09-28T12:42:59Z" level=fatal msg=FAIL**

=================END OF CONTAINER STRUCTURE TESTS==================

**Comment by LakshmiMekala** [comment]
Currently, i could see there is no option to elimitate text in case of failure _"time="2020-09-28T12:42:59Z" level=fatal msg=FAIL"_ as this message is from the test framework. Please refer [documentation](https://github.com/GoogleContainerTools/container-structure-test#flags)

**Comment by rameshpolishetti** [comment]
Referred logs are produced by the docker test frame work, hence not possible to disable.
