### ISSUE TITLE
Make CDD and EAR optional in run_tests.sh . 

### ISSUE THREAD

**Issue by tsaxena18** [TIBCOSoftware/be-tools#121]
$ ./run_tests.sh -h

Usage: run_tests.sh

 [ -i|--image-name]           : Be app image name with tag <image-name>:<tag> ex(be6:v1) [required]

 [ -b|--be-version]           : Be version in x.x format ex(5.6) [required]

 [ -c|--cdd-filename]         : CDD file name ex(fd.cdd) [required]

 [ -e|--ear-filename]         : EAR file name ex(fd.ear) [required]

 [-al|--as-legacy-version]    : Activespaces legacy version in x.x format ex(2.4) [optional]

 [-as|--as-version]           : Activespaces version in x.x format ex(4.4) [optional]

 [ -f|--ftl-version]          : Ftl version in x.x format ex(6.4) [optional]

 [-kv|--key-value-pair]       : Key value pairs to replace in yaml files ex(JRE_VERSION=11) can be multiple [optional]

 [ -h|--help]                 : Print the usage of script [optional]

 NOTE : supply long options with '='

**If possible**, make CDD and EAR file as optional in command, since user may not recall the name of the artifacts for older images. The presence of CDD and EAR file should be checked by default even if user does not provide those.

**Comment by nareshkumarthota** [comment]
CDD and EAR information is available in environment variables. Same can be used to test cdd and ear existence. Changes made available in branch  `fix-dockertest-issues`.
