### ISSUE TITLE
run_tests.sh : Differentiate test between AS and AS legacy.

### ISSUE THREAD

**Issue by tsaxena18** [TIBCOSoftware/be-tools#122]
$ ./run_tests.sh -i fdsnas2:v101 -b 6.0 -c fdstore.cdd -e fdstore.ear -al 2.4 -as 4.4 -f 6.4

=================RUNNING CONTAINER STRUCTURE TESTS=================

INFO: image name:          [fdsnas2:v101]
INFO: be version:          [6.0]
INFO: cdd file name:       [fdstore.cdd]
INFO: ear file name:       [fdstore.ear]
INFO: as legacy version:   [2.4]
INFO: as version:          [4.4]
INFO: ftl version:         [6.4]

====== Test file: be.yaml ======
====== Test file: aslegacy.yaml ======
====== Test file: as.yaml ======
====== Test file: ftl.yaml ======

=== RUN: Command Test: beengine without cdd
--- PASS
duration: 3.350061403s
=== RUN: File Content Test: BE TRA Updated with AS home
--- PASS
duration: 0s
=== RUN: File Existence Test: BE Path
--- PASS
duration: 0s
=== RUN: File Existence Test: BE Engine Binary
--- PASS
duration: 0s
=== RUN: File Existence Test: BE Engine TRA File
--- PASS
duration: 0s
=== RUN: File Existence Test: BE Path Lib
--- PASS
duration: 0s
=== RUN: File Existence Test: BE Lib File
--- PASS
duration: 0s
=== RUN: File Existence Test: Gvproviders Path
--- PASS
duration: 0s
=== RUN: File Existence Test: Gvproviders File
--- PASS
duration: 0s
=== RUN: File Existence Test: Gvproviders Consul
--- PASS
duration: 0s
=== RUN: File Existence Test: Gvproviders Consul File
--- PASS
duration: 0s
=== RUN: File Existence Test: Docker Run File
--- PASS
duration: 0s
=== RUN: File Existence Test: Cdd file
--- PASS
duration: 0s
=== RUN: File Existence Test: Ear file
--- PASS
duration: 0s
=== RUN: File Existence Test: Cdd file
--- PASS
duration: 0s
=== RUN: File Existence Test: Ear file
--- PASS
duration: 0s
=== RUN: Metadata Test
--- PASS
duration: 0s
=== RUN: File Content Test: BE TRA Updated with AS home
--- PASS
duration: 0s
=== RUN: File Existence **Test: AS Lib Path**
--- PASS
duration: 0s
=== RUN: File Existence **Test: AS Lib Jar File**
--- PASS
duration: 0s
=== RUN: File Content Test: BE TRA Updated with AS home
--- PASS
duration: 0s
=== RUN: File Existence **Test: AS Lib Path**
--- PASS
duration: 0s
=== RUN: File Existence **Test: AS Lib Jar File**
--- PASS
duration: 0s
=== RUN: File Content Test: BE TRA Updated with FTL home
--- PASS
duration: 0s
=== RUN: File Existence Test: FTL Lib Path
--- PASS
duration: 0s
=== RUN: File Existence Test: FTL Lib Jar File
--- PASS
duration: 0s

============ RESULTS ============

Passes:      26
Failures:    0
Duration:    3.350061403s
Total tests: 26

PASS

=================END OF CONTAINER STRUCTURE TESTS==================

**Comment by LakshmiMekala** [comment]
Fixed in branch [fix-dockertest-issues](https://github.com/TIBCOSoftware/be-tools/tree/fix-dockertest-issues)

**Comment by tsaxena18** [comment]
Confirmed, the legacy AS and ActiveSpaces name are different now.
[apps@beqacentos7 tests]$ sh run_tests.sh -i fdsnas2:v101 -b 6.0  -al 2.4 -as 4.4 -f 6.4

=================RUNNING CONTAINER STRUCTURE TESTS=================

-----------------------------------------------
INFO: image name:          [fdsnas2:v101]
INFO: be version:          [6.0]
INFO: as legacy version:   [2.4]
INFO: as version:          [4.4]
INFO: ftl version:         [6.4]
-----------------------------------------------


================================
====== Test file: be.yaml ======
================================

======================================
====== Test file: aslegacy.yaml ======
======================================

================================
====== Test file: as.yaml ======
================================

=================================
====== Test file: ftl.yaml ======
=================================
=== RUN: Command Test: beengine without cdd
--- PASS
duration: 3.102081945s
=== RUN: File Content Test: BE TRA Updated with AS home
--- PASS
duration: 0s
=== RUN: File Existence Test: BE Path
--- PASS
duration: 0s
=== RUN: File Existence Test: BE Engine Binary
--- PASS
duration: 0s
=== RUN: File Existence Test: BE Engine TRA File
--- PASS
duration: 0s
=== RUN: File Existence Test: BE Path Lib
--- PASS
duration: 0s
=== RUN: File Existence Test: BE Lib File
--- PASS
duration: 0s
=== RUN: File Existence Test: Gvproviders Path
--- PASS
duration: 0s
=== RUN: File Existence Test: Gvproviders File
--- PASS
duration: 0s
=== RUN: File Existence Test: Docker Run File
--- PASS
duration: 0s
=== RUN: File Existence Test: Cdd file
--- PASS
duration: 0s
=== RUN: File Existence Test: Ear file
--- PASS
duration: 0s
=== RUN: Metadata Test
--- PASS
duration: 0s
=== RUN: File Content Test: BE TRA Updated with AS home
--- PASS
duration: 0s
=== RUN: File Existence Test: AS Lib Path
--- PASS
duration: 0s
=== RUN: File Existence Test: AS Lib Jar File
--- PASS
duration: 0s
=== RUN: File Content Test: BE TRA Updated with ACTIVESPACES home
--- PASS
duration: 0s
=== RUN: File Existence Test: ACTIVESPACES Lib Path
--- PASS
duration: 0s
=== RUN: File Existence Test: ACTIVESPACES Lib Jar File
--- PASS
duration: 0s
=== RUN: File Content Test: BE TRA Updated with FTL home
--- PASS
duration: 0s
=== RUN: File Existence Test: FTL Lib Path
--- PASS
duration: 0s
=== RUN: File Existence Test: FTL Lib Jar File
--- PASS
duration: 0s

=================================
============ RESULTS ============
=================================
Passes:      22
Failures:    0
Duration:    3.102081945s
Total tests: 22

PASS

=================END OF CONTAINER STRUCTURE TESTS==================
