### ISSUE TITLE
run_tests.sh : Add tests for the verification of external jars.

### ISSUE THREAD

**Issue by tsaxena18** [TIBCOSoftware/be-tools#123]
There are no tests or any verifications for the presence of external jars like jms.jar, ojdbc7.jar, etc in BE container.

$ ./run_tests.sh -h

Usage: run_tests.sh

 [ -i|--image-name]           : Be app image name with tag <image-name>:<tag> ex(be6:v1) [required]

 [ -b|--be-version]           : Be version in x.x format ex(5.6) [required]

 [ -c|--cdd-filename]         : CDD file name ex(fd.cdd) [required]

 [ -e|--ear-filename]         : EAR file name ex(fd.ear) [required]

 [-al|--as-legacy-version]    : Activespaces legacy version in x.x format ex(2.4) [optional]

 [-as|--as-version]           : Activespaces version in x.x format ex(4.4) [optional]

 [ -f|--ftl-version]          : Ftl version in x.x format ex(6.4) [optional]

 [-kv|--key-value-pair]       : Key value pairs to replace in yaml files ex(JRE_VERSION=11) can be multiple [optional]

 [ -h|--help]                 : Print the usage of script [optional]

 NOTE : supply long options with '='

**Comment by rameshpolishetti** [comment]
@tsaxena18 since external jars are optional artefacts in the BE app container, test cases are not there.

**Comment by rameshpolishetti** [comment]
@tsaxena18 as discussed, closing the issue.
