### ISSUE TITLE
Support for Ignite Cluster Manager type

### ISSUE THREAD

**Issue by vshende-tibco** [TIBCOSoftware/be-tools#127]
With 6.1.0, BE will now support Ignite Cluster as a cluster provider. This will enable additional topologies to be supported in BE. 
Details here => https://confluence.tibco.com/display/be/Ignite+Cluster+Provider

**Comment by LakshmiMekala** [comment]
Here is the desin approach for the ignite cluster integration with helm
1. Proposing cmType=IGNITE
2. Add support for bsType=None/sharednothing/store and storeType=RDBMS/Cassandra/AS4

Please review and let us know your feedback @vpatil-tibco @vivekshende

**Comment by vpatil-tibco** [comment]
1. Yes that is fine. The behavior should be same as what we have to AS2x as Cluster+cache. So if the cmType=IGNITE then the cache defaults to IGNITE as well.
2. This should as is, stays the same, nothing new for IGNITE.

**Comment by LakshmiMekala** [comment]
Helm scripts now support ignite as a cluster provider. For ignite code changes please refer to branch [feature-ignite-helm](https://github.com/TIBCOSoftware/be-tools/tree/feature-ignite-helm). Also added helm template tests for ignite cluster.

**Comment by jgirase** [comment]
We have verified following supported configurations with Ignite cluster provider using helm chart,

- Persistence None,Shared nothing
- Stores - MySQL DB, AS4, Cassandra

**Comment by rameshpolishetti** [comment]
Closing the issue as it is validated successfully.
