### ISSUE TITLE
Support for Fargate deployment using helm chart

### ISSUE THREAD

**Issue by rameshpolishetti** [TIBCOSoftware/be-tools#131]
Add support to deploy BE application into the AWS Fargate environment using helm chart.

**Comment by rameshpolishetti** [comment]
This enhancement is available at https://github.com/TIBCOSoftware/be-tools/tree/docker-scripts-improvements

**Comment by ykalidin** [comment]
Verified by Tanmay as mentioned in the [PR130](https://github.com/TIBCOSoftware/be-tools/pull/130).
Added required notes for load balancer creation in the documentation. Available in `docs610` branch in be-tools.wiki.
