### ISSUE TITLE
Unable to complete build steps following instructions

### ISSUE THREAD

**Issue by mmussett** [TIBCOSoftware/be-tools#134]
In the build steps it mentions running s2i, however i cannot locate this command in the repository. There's no mention of having to download any dependencies other than BE image files.

**Comment by ykalidin** [comment]
Available in `Building TIBCO BusinessEvents Application Docker Image` and `Before You Begin` documents in wiki `docs610`
branch. Verified.

**Comment by vilasshelar** [comment]
Verified.Can be closed

**Comment by rameshpolishetti** [comment]
@mmussett inputs are taken care and updated docs are verified successfully. Closing the issue.
