### ISSUE TITLE
Add support to deploy BE application into OCI

### ISSUE THREAD

**Issue by rameshpolishetti** [TIBCOSoftware/be-tools#135]
Add support to deploy BE application into OCI (Oracle Cloud Infrastructure). This includes:

- Update helm chart configurations, values.yaml OR documentation if required
- Update wiki-documentation

**Comment by LakshmiMekala** [comment]
BE Application now supports deployment into OCI.

Currently documentation is under internal review. Please refer [here](https://github.com/TIBCOSoftware/be-tools/blob/docs-wiki/docs/Oracle%20Container%20Engine%20Kubernetes.md). We will add to wiki once internal review is completed

**Comment by LakshmiMekala** [comment]
Documentation for OCI deployment is made available in [wiki for OCI](https://github.com/TIBCOSoftware/be-tools/wiki/Oracle%20Container%20Engine%20Kubernetes)

**Comment by LakshmiMekala** [comment]
Closing the ticket, as doc is available in wiki
