### ISSUE TITLE
Update values.yaml for GV  when Ignite cluster provider is used and storageclass in case of Amazon EKS

### ISSUE THREAD

**Issue by jgirase** [TIBCOSoftware/be-tools#140]
This issue is reported to handle two problems as below,
1.The GV defined in values.yaml file for Ignite discovery url and ports are different than bundled FDCache/FDStore examples cdd files as IgniteClusterStore.cdd. User need to update either yaml file or project if deployment needs to be tested with Ignite cluster provider. Kindly make it consistent for easy configuration.
2.The storage class defined for shared nothing configuration is "standard" in values.yaml file which does not work on AWS EKS. So please add a note or comment to use "aws-efs" as storage class in case of AWS deployments so that user will not run into troubles.

**Comment by rameshpolishetti** [comment]
The fix is available at https://github.com/TIBCOSoftware/be-tools/tree/docker-scripts-improvements

**Comment by jgirase** [comment]
I could see the mentioned changes in values.yaml so closing it. 
Verified it using branch https://github.com/TIBCOSoftware/be-tools/tree/docker-scripts-improvements
