### ISSUE TITLE
Logs shows incorrect cache nodes count when replicas set to 2 for cache agent for EKS deployment with Ignite cluster provider

### ISSUE THREAD

**Issue by jgirase** [TIBCOSoftware/be-tools#144]
Steps:
1.Build image of FDStore/FDCache example with configuration Ignite cluster provider + Ignite cache + AS4/Cassandra store or persistence none using existing installation home.
2.Push the image to ECR and perform required AS4 grid/Cassandra setup
3.Set replicas=2 for cache node
4.Deploy the application using helm chart.
5.Check cache/inference pod logs, it shows incorrect cache node count,ideally it should show Currently known [cache-class] agents = 2 however it shows 1.
Inference agent gets connected to first cache node but second cache node forms its own cluster.
Find attached logs for reference.
[fdstore_As4_memberissue.zip](https://github.com/TIBCOSoftware/be-tools/files/5653036/fdstore_As4_memberissue.zip)

**Comment by dijadhav** [comment]
#148 Check this also

**Comment by LakshmiMekala** [comment]
Fixed issue, please validate

**Comment by jgirase** [comment]
Verified with branch fix-issue-144.
Ran scenarios like persistence none, Stores as AS4 and Cassandra with Ignite cluster provider with replicas=2/3.
Find attached logs for reference.
[logs_Issue144.zip](https://github.com/TIBCOSoftware/be-tools/files/5694499/logs_Issue144.zip)
