### ISSUE TITLE
Update helm configuration for metric type influx as per version 2.0 as that will be the only supported version in BE 6.1.0

### ISSUE THREAD

**Issue by jgirase** [TIBCOSoftware/be-tools#145]
In 6.1.0 influxDB version 2.0 will be supported so helm configuration need to change accordingly.
Kindly refer the bundled readme.html for example FraudDetectionInfluxDB for steps.
The values.yaml has influx configuration as per version 1.x which needs to be updated as per version 2.0
If the bundled example tried to run with existing helm setup it fails to connect to influxDB server.
Also the steps mentioned in bundled readme.html does not work with influx helm chart 1.8.0

**Comment by LakshmiMekala** [comment]
Fixed issue with PR #146 

@jgirase please validate the fix

**Comment by jgirase** [comment]
Verified the fix with branch be-tools-fix-issue-145
Find attached logs and screenshots for reference.
[inf.log](https://github.com/TIBCOSoftware/be-tools/files/5678823/inf.log)
![Screenshot from 2020-12-11 16-18-47](https://user-images.githubusercontent.com/13216640/101897293-5463e000-3bd0-11eb-9f92-30dbc3c3b84b.png)

**Comment by jgirase** [comment]
Verified the fix with branch be-tools-fix-issue-145
Find attached logs and screenshots for reference.
[inf.log](https://github.com/TIBCOSoftware/be-tools/files/5678831/inf.log)
![Screenshot from 2020-12-11 16-49-08](https://user-images.githubusercontent.com/13216640/101897635-db18bd00-3bd0-11eb-830b-d947e1bd4aae.png)

**Comment by jgirase** [comment]
Already verified so closing it
