### ISSUE TITLE
Ignite properties for k8s

### ISSUE THREAD

**Issue by dijadhav** [TIBCOSoftware/be-tools#148]
To run the BE engine with ignite cluster in k8s following properties are required
1) tra.be.ignite.discovery.type - Type of the discovery . Current supported values are (k8s) (required)
2) tra.be.ignite.k8s.namespace - The namespace the Kubernetes service belongs to. Default value is default
3) tra.be.ignite.k8s.service.name - Name of Kubernetes service for Ignite pods' IP addresses lookup. The name of the service must be equal to the name set in service's Kubernetes configuration. Default value is ignite
4) tra.be.ignite.k8s.master.url - Host name of the Kubernetes API server. Default value is https://kubernetes.default.svc.cluster.local:443
5) tra.be.ignite.k8s.account.token -  The path to the service token file.Default value is 
/var/run/secrets/kubernetes.io/serviceaccount/token

**Comment by LakshmiMekala** [comment]
Added ignite properties to values.yaml files. Closing this issue.
