### ISSUE TITLE
Parameters layout are not proper in BE engine logs when run as Windows container.

### ISSUE THREAD

**Issue by tsaxena18** [TIBCOSoftware/be-tools#150]
The initial listing of parameters is not displayed correctly and contains errors as described below : 

C:\Share\be-tools-docker-scripts-improvements\cloud\docker>docker logs cache
JMX_PORT: 5555
BE_HOME: c:/tibco/be/6.1
TRA FILE: c:/tibco/be/6.1\bin\be-engine.tra
ENGINE NAME: be-engine
CDD FILE: c:/tibco/be/application/fdcache.cdd
PROCESSING UNIT: cache
EAR FILE: c:/tibco/be/application/ear/fdcache.ear
AS DISCOVER URL: tcp://210F92A8E5A5:50000
AS LISTEN URL: tcp://210F92A8E5A5:50000
'Copyright' is not recognized as an internal or external command,
operable program or batch file.
'This' is not recognized as an internal or external command,
operable program or batch file.
'ocal' is not recognized as an internal or external command,
operable program or batch file.
'GVPROVIDER' is not recognized as an internal or external command,
operable program or batch file.
'GVPROVIDER!' is not recognized as an internal or external command,
operable program or batch file.
't' is not recognized as an internal or external command,
operable program or batch file.
'ho' is not recognized as an internal or external command,
operable program or batch file.
The system cannot find the path specified.
'RRORLEVEL' is not recognized as an internal or external command,
operable program or batch file.
't' is not recognized as an internal or external command,
operable program or batch file.
't' is not recognized as an internal or external command,
operable program or batch file.
'E_PROPS_FILE' is not recognized as an internal or external command,
operable program or batch file.
'XIST' is not recognized as an internal or external command,
operable program or batch file.
'-r' is not recognized as an internal or external command,
operable program or batch file.
't' is not recognized as an internal or external command,
operable program or batch file.
An incorrect parameter was
entered for the command.
'o' is not recognized as an internal or external command,
operable program or batch file.
WARN: 0[zero] GV values fetched from the GV provider[!GVPROVIDER!]

Attached cache log for the reference. 
[cache-win.txt](https://github.com/TIBCOSoftware/be-tools/files/5707878/cache-win.txt)

**Comment by nareshkumarthota** [comment]
fix updated in `docker-scripts-improvements`. Kindly validate.

**Comment by tsaxena18** [comment]
Verified the fix by running cache container from images built with Installers as well as from Installation and the logs are fine.
Attached docker run log for the reference.
[cache-win-pr150.txt](https://github.com/TIBCOSoftware/be-tools/files/5715116/cache-win-pr150.txt)
