### ISSUE TITLE
Getting error on helm deployment for mysql/efs-provisioner charts which are deprecated

### ISSUE THREAD

**Issue by jgirase** [TIBCOSoftware/be-tools#152]
Got following error on helm deployment,
Error: found in Chart.yaml, but missing in charts/ directory: mysql, efs-provisioner
helm.go:94: [debug] found in Chart.yaml, but missing in charts/ directory: mysql, efs-provisioner

Above two charts are not getting downloaded and a zip file named deprecation-0.2.2.tgz gets downloaded.

Even those two charts copied manually deployment fails with error as below,

Error: template: BE Helm Chart/charts/deprecation/templates/NOTES.txt:10:3: executing "BE Helm Chart/charts/deprecation/templates/NOTES.txt" at <fail "\n*******************************************************\n* This chart location is deprecated. Learn more here: *\n* https://helm.sh/blog/charts-repo-deprecation/       *\n*******************************************************\n">: error calling fail: 
*******************************************************
* This chart location is deprecated. Learn more here: *
* https://helm.sh/blog/charts-repo-deprecation/       *
*******************************************************

So need a solution for above two charts to use them in deployments

**Comment by LakshmiMekala** [comment]
Helm chart support for github.com/helm/charts/stable is deprecated.
As a temporary fix we are disabling dependency charts for mysql and efs-provisioner. Created PR #151

**Comment by rameshpolishetti** [comment]
@jgirase This issue is coming because helm stable repositories are no longer available at https://kubernetes-charts.storage.googleapis.com. Until we find alternative charts for mysql & efs, respective chart archives are added to charts/ folder. With this user can directly deploy the app using `helm install` without `helm dep update` 

Fix is available in the branch `docker-scripts-improvements`

**Comment by jgirase** [comment]
Dependant charts are present now in charts folder as below,
~/Downloads/be-tools-docker-scripts-improvements/cloud/kubernetes/helm/charts$ ls
efs-provisioner-0.11.0.tgz  grafana-6.1.14.tgz  influxdb-4.8.4.tgz  mysql-1.6.2.tgz

No error on helm deployment now,
~/Downloads/be-tools-docker-scripts-improvements/cloud/kubernetes/helm$ helm install test-helm .
NAME: test-helm
LAST DEPLOYED: Fri Dec 18 19:00:08 2020
NAMESPACE: default
STATUS: deployed
REVISION: 1
NOTES:
Thank you for installing BE Helm Chart.

# Your release is named 'test-helm' and deployed into 'aws' with Cluster type 'ignite' and OM type 'cache'.
