### ISSUE TITLE
Need an option to exclude FTL and AS4x installation home when building image from local installation.

### ISSUE THREAD

**Issue by tsaxena18** [TIBCOSoftware/be-tools#154]
We need to include an option or a flag in docker build command to exclude FTL and AS4x installation home when building image using source as BE installation. Currently the script automatically detects the FTL and AS4x home and user cannot exclude those in creating image. If user needs to build the image using legacy AS then FTL and As4x are not required and vice-versa.

C:\Share\be-tools-docker-scripts-improvements\cloud\docker>build_image.bat -i app -a C:\Share\Work_610\temp -s C:\Share\BE_610_v64\be\6.1 -t fdci:v64fi

INFO: Supplied/Derived Data:

INFO: APPLICATION DATA DIRECTORY   : [C:\Share\Work_610\temp]
INFO: BE HOME                      : [C:\Share\BE_610_v64\be\6.1]
INFO: BE VERSION                   : [6.1.0]
INFO: AS LEGACY HOME               : [C:/Share/BE_610_v64/as/2.4]
**INFO: FTL HOME                     : [C:/Share/FTL/6.5]
INFO: AS HOME                      : [C:/Share/AS/4.5]**
INFO: CDD FILE NAME                : [IgniteClusterDeploy.cdd]
INFO: EAR FILE NAME                : [fdcache.ear]
INFO: DOCKERFILE                   : [.\dockerfiles\Dockerfile_fromtar.win]
INFO: IMAGE TAG                    : [fdci:v64fi]
INFO: JRE VERSION                  : [11]

WARN: Local machine contains both FTL and Activespaces(legacy) installations. Removing unused installation improves the docker image size.

INFO: Adding [be\6.1] to tibcohome.
INFO: Adding [as\2.4] to tibcohome.
**INFO: Adding [ftl\6.5] to tibcohome.
INFO: Adding [as\4.5] to tibcohome.**

**Comment by rameshpolishetti** [comment]
@tsaxena18 Looks like your be-engine.tra defines FTL, AS & ASLegacy home path variables.

Scripts include FTL/AS/ASLegacy artifacts only if they are referred in the be-engine.tra, hence explicit flags are not required.

**Comment by tsaxena18** [comment]
@rameshpolishetti , Yes my be-engine.tra contains those values. But still it does not make sense to include FTL, AS4x installation if my application is based on legacy AS. Using installers we have the option to remove the FTL, AS4x installers from source but here we do not hve any control.

**Comment by rameshpolishetti** [comment]
@tsaxena18 In an ideal scenario does the be-engine.tra contains all home paths (FTL, AS4x & ASLegacy) when the application is based on ASLegacy?
For second note: Yes in case of `build from installers` you can keep only required installers under the source folder, the same can be achieved in case of `build from local installation` by updating only required home paths (among FTL, AS4x & ASLegacy) in the be-engine.tra

Currently, scripts automatically identify required artifacts by inspecting be-engine.tra. Adding additional flags for each FTL, AS4x & ASLegacy would mean removing this intelligence.

Adding @vpatil-tibco to share his view on this.

**Comment by tsaxena18** [comment]
It is not required to have FTL and AS4x installations set in be-engine.tra for application based on legacy AS but it is critical when image size is in question. If flag is not the option then we should add a note about this in the docs in case of build from local installation with regard to image size.

**Comment by tsaxena18** [comment]
I have updated the title and original summary as it is applicable to both Windows and Linux scripts.

**Comment by nareshkumarthota** [comment]
@tsaxena18  Comment updated in wiki docs. Check [here](https://github.com/TIBCOSoftware/be-tools/wiki/Before-You-Begin).

**Comment by tsaxena18** [comment]
Confirmed. The note has been included in the docs which says,
"When building image from local installation, build script looks for FTL_HOME, ACTIVESPACES_HOME & AS_HOME in the be-engine.tra, If they are defined with valid paths, respective artefacts are copied into the image. If you want to include/exclude any of them in the docker image make sure the path is updated/emptied properly for the respective field."
