### ISSUE TITLE
Find alternative helm chart repositories for mysql & efs

### ISSUE THREAD

**Issue by rameshpolishetti** [TIBCOSoftware/be-tools#156]
Currently, BE helm chart depends on mysql & efs helm charts which are hosted at `https://kubernetes-charts.storage.googleapis.com` known as helm stable charts. Now, helm no longer supports stable charts.

Find out alternative helm chart repositories for mysql & efs which work for us.

**Comment by LakshmiMekala** [comment]
fix available in fix-issue-156 branch

**Comment by ykalidin** [comment]
Verified mysql chart, working as expected.
Efs is provided without the helm chart. Verified Efs provisioning in eks cluster working fine.
