### ISSUE TITLE
jq bundled with gvproviders but no licence 

### ISSUE THREAD

**Issue by mmussett** [TIBCOSoftware/be-tools#161]
We've bundling jq in here but i don't see the authors licence which also contributes IBM.

**Comment by rameshpolishetti** [comment]
@mmussett Update `be-tools` license and copied the jq-license alongside `jq` binary for Linux containers.

For Windows containers, we use windows PowerShell chocolatey package manager instead of directly downloading the `jq` binary. Hence I feel no action required in this case.
