### ISSUE TITLE
Support for SAML Authentication for AWS GV Provider

### ISSUE THREAD

**Issue by mmussett** [TIBCOSoftware/be-tools#163]
**Context**

As well as AWS Credentials (key+secret) as authentication type we need to support SAML as another authentication type.

With SAML Authentication, will need provide the following values to be able to connect to AWS Secrets Manager Service

- Identity Provider (IdP) Type - ADFS 
- Identity Provider Login URL - Example URL for ADFS: https://<host>:<port>/adfs/ls/ IdpInitiatedSignOn.aspx? loginToRp=urn:amazon: webservices
- Username - Username that is configured with IdP
- Password - Password that is configured with IdP
- AWS Role - AWS IAM Role

**Comment by rameshpolishetti** [comment]
SAML authenticated AWS GV provider implementation is available under the branch `feature-gv-provider-saml-aws`:
https://github.com/TIBCOSoftware/be-tools/tree/feature-gv-provider-saml-aws/cloud/docker/gvproviders/custom/samlaws

Follow below steps to try this GV:

build BE app image:
```sh
./build_image.sh \
-i app \
-s /home/user/tibco/installers \
--gv-provider samlaws \
-t fd:latest
```

run BE app:
```sh
docker run \
  -e AWS_SM_SECRET_ID=<AWS SECRETS MANAGER - SECRET ID> \
  -e AWS_DEFAULT_REGION=<REGION> \
  -e AWS_ROLE_ARN=<AWS IAM role>
  -e SAML_IDP_URL=<IdP login URL> \
  -e SAML_USERNAME=<user name> \
  -e SAML_PASSWORD=<password> \
  fd:latest
```
