### ISSUE TITLE
Support for AWS Systems Manager Params Store

### ISSUE THREAD

**Issue by mmussett** [TIBCOSoftware/be-tools#164]
**Context**

Currently GV Framework only supports pulling values from AWS Secrets Manager for both Credentials (Passwords) and non-credential configuration values.

We need to be able to support separation of concern for what is credential data (i.e. passwords) from  parameters such that any Global Variables that are of type password are retrieved from AWS Secrets Manager and all other types are retrieved from AWS Systems Manager Param Store

**Comment by vpatil-tibco** [comment]
The infrastructure is now available to include multiple resources to maintain GV's across a project. As far as the specific implementation goes, there are some available OOB, for others, end users are free to implement it looking at other implementations or wait till its available OOB.
