### ISSUE TITLE
Upgrading the BE app using helm is failing

### ISSUE THREAD

**Issue by rameshpolishetti** [TIBCOSoftware/be-tools#167]
Upgrading the BE app using `helm` is failing, following are steps to reproduce the issue:

1. Install the BE app using _helm install myapp ._
2. Update values.yaml with new values (lets replicaCount: 1 to 2)
3. Upgrade the BE app using _helm upgrade myapp ._

**Actual behavior**:
_Error: UPGRADE FAILED: failed to create patch: map: map[] does not contain declared merge key: name_

**Expected behavior**:
BE app upgrade should be successful

**Comment by LakshmiMekala** [comment]
Fixed issue in branch [fix-issue-167](https://github.com/TIBCOSoftware/be-tools/tree/fix-issue-167)

**Comment by ykalidin** [comment]
Working as expected, verified by upgrading replicas for below cases:
Image without pullsecret
Image with secret
Image with registry credentials
