### ISSUE TITLE
Mention allowed 'cpType' parameter values  for Oracle Cloud in Wiki/Helm values.yaml

### ISSUE THREAD

**Issue by AdittyThakare** [TIBCOSoftware/be-tools#171]
Currently we have not mentioned valid values for 'cpType' parameter w.r.t Oracle Cloud, have tested with value as 'oci'. We have mentioned values for other cloud providers as follows in Helm->values.yaml file:

#Required parameter to be passed for all cloud providers
cpType: minikube      #cpType can be minikube, aws, awsfargate, azure, openshift OR gcp

Please document the valid values for 'cpType' parameter for Oracle Cloud in Wiki and Helm/values.yaml as well.

**Comment by LakshmiMekala** [comment]
Added cpType as oci in values.yaml. Fixed with PR #170
