### ISSUE TITLE
Build_Image : Unit tests did not run.

### ISSUE THREAD

**Issue by tsaxena18** [TIBCOSoftware/be-tools#174]
### Version Information
| Software       | Version(s)     |
| -------------- | -------------- |
| BusinessEvents |    6.1.0            |
| OS Type?       |     Linux           |
| OS Version?    |    CentOS 7.9            |
| Docker         |    20.10.5            |
| Kubernetes     |   NA             |
| Helm           |       NA         |

### What is the expected behavior?
The docker image build process should be successfully completed without any error. 

### What is the actual behavior?
The docker image is created fine but the process exits with error as described below : 

Total reclaimed space: 6.588GB
INFO: Deleting folder: [tmp_2811].
INFO: Docker build successful. Image Name: [fdsamysql:610Ign]
**build_image.sh: line 780: source: run_tests.sh: file not found**

So it can be seen that the unit tests did not run in the end.

### Please provide a unit test that demonstrates the bug.
1. Prepare CDD and EAR file for a BE app which run with Ignite as cluster provider.
2. Create docker image with command as described below :
sh build_image.sh -i app -a /home/apps/Testing/temp610/SA -s /home/apps/Installers/BE/610 -t fdsamysql:610Ign
3. Check last line when the process exits.

### Please provide log files.
[ErrorPR170.txt](https://github.com/TIBCOSoftware/be-tools/files/6076137/ErrorPR170.txt)

**Comment by nareshkumarthota** [comment]
In `sh` shell  `source` command not available. Try using `bash` or `/bin/bash` before  `build_image.sh`

**Comment by tsaxena18** [comment]
When we run the command using ./ instead using sh , it went fine. No error. Unit tests ran successfully.
./build_image.sh -i app -a /home/apps/Testing/temp610/SA -s /home/apps/Installers/BE/610 -t fdsamysql:610Ign2

**Comment by tsaxena18** [comment]
Does it require any adjustment in scripts (for running on diff. OS) or shall I close it ?

**Comment by nareshkumarthota** [comment]
In General or As per documentation execution of script should be done using `./`. Adjustments or not required you can close this issue.

**Comment by tsaxena18** [comment]
Closing as per comments.
