### ISSUE TITLE
Update AS 2.x compatibility versions in asleg.bat/sh

### ISSUE THREAD

**Issue by AdittyThakare** [TIBCOSoftware/be-tools#180]
Encountering following error while building docker image with BE 6.1.1 and AS 2.4.1. 
```
[INFO] --- be-maven-plugin:6.1.1:buildAppImage (default-buildAppImage) @ FraudDetectionCache ---
Command to be executed:C:/Installation/BE/6.1.1/V17/be/6.1/cloud/docker/build_image.bat -i app -a C:\Docker\target -s C:\Docker\Installer -t fdc:test
ERROR: BE version: [6.1.1] not compatible with Activespaces legacy version: [2.4.1].
Missing operand.
Missing operand.
 exitValue() 1
```
Kindly update the asleg.bat/sh to include following entries:
set VALID_AS_LEG_MAP_MAX[6.1.1]=2.4.0
set VALID_AS_LEG_MAP_MAX[6.1.1]=2.4.1

We dont support AS 2.3.0 in BE 6.0.0 and BE 6.1.0 releases So please remove entries for AS 2.3.0 and include entries for 2.4.0 with 6.0.0 and 6.1.0.

**Comment by nareshkumarthota** [comment]
Changes available in branch `feature-oci-image-buildtool`.

**Comment by AdittyThakare** [comment]
Docker images are successfully getting built with BE 6.1.1 + AS 2.4.1 now. Adding docker build logs for FDCache application.
[Windows_fdc_V25.txt](https://github.com/TIBCOSoftware/be-tools/files/6383813/Windows_fdc_V25.txt)
