### ISSUE TITLE
Wiki/Readme update to use abstract content for containerization

### ISSUE THREAD

**Issue by vpatil-tibco** [TIBCOSoftware/be-tools#181]
**Context**
Currently all our documentation is around "dockerization of BE application", with OCI + non docker runtime we now have alternative containerization and/or runtime support (via #147). Our documentation should reflect the same, i.e. abstract it at the containerization level with options to go docker or non docker route.

**Alternatives**
No

**Has the feature been requested before?**
Yes via #147. This is more to complement the feature with appropriate documentation changes.

**If the feature request is approved, would you be willing to submit a PR?**
Yes

**Comment by nareshkumarthota** [comment]
@vpatil-tibco  Docs updated in wiki. Kindly review and close this issue.

**Comment by rameshpolishetti** [comment]
Closing the issue as wiki documentation has been updated.
