### ISSUE TITLE
Buildah - Getting warning for missing "BE_PRODUCT_EDITION" build argument.

### ISSUE THREAD

**Issue by tsaxena18** [TIBCOSoftware/be-tools#182]
### Version Information
| Software       | Version(s)     |
| -------------- | -------------- |
| BusinessEvents |        6.1.1        |
| OS Type?       |      CentOS          |
| OS Version?    |    7.9            |
| Docker         |          20.10.5      |
| Kubernetes     |     NA           |
| Helm           |     NA           |

### What is the expected behavior?
The buildah image build log should be clean. 

### What is the actual behavior?
Getting warning for missing "BE_PRODUCT_EDITION" build argument. Look in the log for below statement.
WARN missing "BE_PRODUCT_EDITION" build argument. Try adding "--build-arg BE_PRODUCT_EDITION=<VALUE>" to the command line

### Please provide a unit test that demonstrates the bug.
Run the image build utility with build-tool type as buildah.
 
### Other notes on how to reproduce the issue?
Not required.

### Please provide log files.
[buildah.txt](https://github.com/TIBCOSoftware/be-tools/files/6293875/buildah.txt)

**Comment by nareshkumarthota** [comment]
Can you try again by taking latest changes.

**Comment by tsaxena18** [comment]
Agree fixed.
The warning is no longer present in build log.
Attached log for the reference.
[AfterFix.txt](https://github.com/TIBCOSoftware/be-tools/files/6315273/AfterFix.txt)
