### ISSUE TITLE
Build time is longer for both tools (Docker & Buildah).

### ISSUE THREAD

**Issue by tsaxena18** [TIBCOSoftware/be-tools#183]
### Version Information
| Software       | Version(s)     |
| -------------- | -------------- |
| BusinessEvents |    6.1.1            |
| OS Type?       |       CentOS         |
| OS Version?    |       7.9         |
| Docker         |     20.10.5           |
| Kubernetes     |     NA           |
| Helm           |      NA          |

### What is the expected behavior?
The image build time should be less and similar to what we already have with the previous version. 
Installers --> BE Enterprise + BE Process Add-on + ActiveSpaces 2.4.1

### What is the actual behavior?
The image build time from both tools docker as well as buildah is much longer. All tests are performed on same machine.
Before, the avg duration was approx. **7 min**.
Now with branch **feature-oci-image-buildtool**, the docker image build time is approx. **18 min** and for buildah it is approx. **25 min**.
 
### Please provide log files.
[docker.txt](https://github.com/TIBCOSoftware/be-tools/files/6294080/docker.txt)

**Comment by tsaxena18** [comment]
This is my observation across BE 6.0.0, 6.1.0 and 6.1.1 (built images with same branch feature-oci-image-buildtool). All the tests performed on same machine - physical CentOS. I have cleaned up cache (docker system prune, etc) before performing these tests.
The time taken by each version of BE with buildtype docker and buildah is listed below : (Used FDCache app with cache as AS2x)

6.0.0 - Docker - 367.6s
6.1.0 - Docker - 422.5s
6.1.1 - Docker - 1108.7s

6.0.0 - Buildah - 434s
6.1.0 - Buildah - 436s
6.1.1 - Buildah - 1192s

Number may vary little bit depending on net speed and these are avg. numbers as I had performed same test twice.

**Comment by LakshmiMekala** [comment]
Tried debugging the build time on centos machine and observed that docker image build on centos is taking 6-9 mins time to build docker image for different versions of BE 5.6,6.0,6.1,6.1.1. However BE 6.1.1 is taking ~20sec longer time to install on centos as well as ubuntu 20.04 machine. Hence resolving the ticket

**Comment by tsaxena18** [comment]
It is mostly BE 6.1.1 installation that is taking most of the time during image build. Hence closing the ticket.
