### ISSUE TITLE
Not able to build docker/buildah images with ActiveSpaces 4.x.

### ISSUE THREAD

**Issue by tsaxena18** [TIBCOSoftware/be-tools#184]
### Version Information
| Software       | Version(s)     |
| -------------- | -------------- |
| BusinessEvents |         6.1.1       |
| OS Type?       |      CentOS          |
| OS Version?    |      7.9          |
| Docker         |    20.10.5            |
| Kubernetes     |      NA          |
| Helm           |       NA         |

### What is the expected behavior?
The application image should be build successfully with AS 4.x installers.

### What is the actual behavior?
The image build utility is failing for both docker and buildah type when AS 4.x installers are present.
1.) sudo ./build_image.sh -i app -a /home/apps/Testing/temp611/None-Ignite  -s /home/apps/Installers/BE/611/v23 -t fdcign:v23 -b buildah
ERROR: BE version: [6.1.1] not compatible with As version: [4.6.0]
2.) sudo ./build_image.sh -i app -a /home/apps/Testing/temp611/None-Ignite  -s /home/apps/Installers/BE/611/v23 -t fdcign:v23 -b buildah
ERROR: BE version: [6.1.1] not compatible with As version: [4.5.0]
 
### Please provide a unit test that demonstrates the bug.
Build the application image with BE installers and AS 4.x installers (4.5 or 4.6).

**Comment by nareshkumarthota** [comment]
for be 6.1.1 supported as version is 4.6.1

**Comment by tsaxena18** [comment]
Confirmed.
The image build process went fine with docker and buildah with suppoted version AS 4.6.1 is used.
