### ISSUE TITLE
Starting from BE 6.1.1 RMS does not have a dependency on AS2

### ISSUE THREAD

**Issue by rameshpolishetti** [TIBCOSoftware/be-tools#186]
**Context**
Currently, the default RMS is configured (and supported) with AS2 Cluster and Cache providers. Starting from BE version 6.1.1, Ignite providers are configured by default.

This implies for BE version 6.1.1 and above, RMS does not have a mandatory dependency on AS2. Update container build scripts to accommodate this behavior. 

**Alternatives**
NA

**Has the feature been requested before?**
NA

**If the feature request is approved, would you be willing to submit a PR?**
YES

**Comment by nareshkumarthota** [comment]
changes pushed into branch `feature-oci-image-buildtool`
