### ISSUE TITLE
Support for AWS Default Credential Chain for GV Framework

### ISSUE THREAD

**Issue by mmussett** [TIBCOSoftware/be-tools#187]
**Context**
When using GV Framework to extract content from AWS configuration services such as Credential Manager we need to be able to use the default credential chain model rather than provide explicit credentials on the command line so that when deployed to ECS Fargate the credentials are passed to the container environment using ECS Task Role model.

**Alternatives**
N/A

**Has the feature been requested before?**
No

**If the feature request is approved, would you be willing to submit a PR?**
Yes / No _(Help can be provided if you need assistance submitting a PR)_

**Comment by ykalidin** [comment]
This feature is available in `chore-update-awsgv` branch

**Comment by rameshpolishetti** [comment]
This can be validated on master branch.

**Comment by tsaxena18** [comment]
Verified AWS based global variables by running docker images locally and also validated AWS ECS by passing AWS secret in ECS task definition and applying required policy to ecsTaskExecutionRole for access to AWS secret, hence not required to pass AWS credentials.

**Comment by tsaxena18** [comment]
Closing it as this was validated on master branch.

**Comment by rameshpolishetti** [comment]
Thank you @tsaxena18. Closing the issue as it is validated successfully.
