### ISSUE TITLE
Allow building RMS image with desired cluster type

### ISSUE THREAD

**Issue by AdittyThakare** [TIBCOSoftware/be-tools#188]
We support RMS with AS2/FTL/Ignite cluster types in 6.1.1 now.

While building RMS image we just pass the installers and not CDD file to pick configuration as desired. Currently, even if we pass FTL/AS2 installers while building RMS image, on docker run could see that RMS is starting with Ignite cluster as we have set Ignite Cluster in the default CDD/EAR.

There should be a way for user to specify desired cluster setting, e.g providing an optional parameter to specify the CDD file.

**Comment by nareshkumarthota** [comment]
By default `RMS.cdd` is configured to `CDD_FILE`.CDD_FILE=/opt/tibco/be/${BE_SHORT_VERSION}/rms/bin/RMS.cdd

**Comment by nareshkumarthota** [comment]
Now in case of rms, flag `--app-location` is made optional. If user supplies cdd and ear those will be used while running the container. If user didn't supply any then deafult `RMS.cdd` and `RMS.ear` is used. Updated code available in branch `feature-oci-image-buildtool`

**Comment by AdittyThakare** [comment]
The Build App Image help section has been updated as follows:
` [-a/--app-location]  :    Path to BE application where cdd, ear & optional supporting jars are present
                           Note: Required if --image-type is "app"
                                 **Optional if --image-type is "rms"**
                                 Ignored  if --image-type is "teagent" or "s2ibuilder"`

Have verified building RMS image by providing custom CDD(Ignite+Ignite+Shared Nothing) using -a parameter with latest code available in branch _feature-oci-image-buildtool_. Closing the issue on basis of this testing.
[RMS_CustomCDD_ImageBuild.txt](https://github.com/TIBCOSoftware/be-tools/files/6390233/RMS_CustomCDD_ImageBuild.txt)
[RMS+Ignite+SN_containerLogs.txt](https://github.com/TIBCOSoftware/be-tools/files/6390234/RMS%2BIgnite%2BSN_containerLogs.txt)

Would be testing RMS image building with all possible cluster/cache/persistence combinations later on, will reopen this in case any issue is encountered.
