### ISSUE TITLE
Support to provide repo authentication with build image utility.

### ISSUE THREAD

**Issue by tsaxena18** [TIBCOSoftware/be-tools#190]
**Context**
What are you trying to do and how would you want to do it differently? Is it something you currently you cannot do? Is this related to an issue/problem?
I am trying to build images with default setting and sometimes I ran into this known issue.
failed to solve with frontend dockerfile.v0: failed to create LLB definition: failed to copy: httpReadSeeker: failed open: unexpected status code https://registry-1.docker.io/v2/library/ubuntu/manifests/sha256:45ff0162921e61c004010a67db1bee7d039a677bed0cb294e61f2b47346d42b3: 429 Too Many Requests - Server message: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
ERROR: Container build failed.

**Alternatives**
Can you achieve the same result by doing it in an alternative way? Is the alternative considerable?
Its a well known issue ---> https://github.com/containrrr/watchtower/issues/669
 
The enhancement is not only to cover this known docker behavior but to work with any repo, local/global/private, etc where a user may require custom or old images.  
 
**Has the feature been requested before?**
No

**Comment by LakshmiMekala** [comment]
@tsaxena18 this is related to [docker](https://www.docker.com/increase-rate-limits) and not related to be-tools. Hence resolving the issue.

**Comment by tsaxena18** [comment]
Closing as per the comments.
