### ISSUE TITLE
RMS image container exiting abruptly when started with Ignite cluster

### ISSUE THREAD

**Issue by AdittyThakare** [TIBCOSoftware/be-tools#191]
RMS image when executed with Ignite Cluster(default RMS.cdd), engine is getting exited abruptly. Tested with BE V29/V34 builds.
Faced same  issue on Windows/Mac OS and CentOS platforms. 

Command executed to run container was as follows:
`docker run --net=n3 -p 8090:8090 -e PU=default -e COMPONENT="rms" -e be.engine.id.useLegacy=true -m 2G -v /home/apps/Docker:/opt/tibco/be/6.1/rms/shared maven_rms:ignite`

Attaching logs for CentOS and Windows platforms.
[docker_rms_ignite_windows.txt](https://github.com/TIBCOSoftware/be-tools/files/6359015/docker_rms_ignite_windows.txt)
[docker_rms_ignite_centos.txt](https://github.com/TIBCOSoftware/be-tools/files/6359017/docker_rms_ignite_centos.txt)

**Note**: On CentOS/MacOS RMS engine started successfully with AS2 cluster.

**Comment by nareshkumarthota** [comment]
This behavior is observed because of memory issue. Try adding ` --cpu-count` and `--memory` params to docker run command. example command looks like `docker run --cpu-count 8  --memory 12g <imagename>`

**Comment by AdittyThakare** [comment]
RMS with Ignite cluster container started successfully after increasing cpu-count/memory parameters. Attaching log for reference.
