### ISSUE TITLE
Add Helm Chart support for RMS/TEA

### ISSUE THREAD

**Issue by AdittyThakare** [TIBCOSoftware/be-tools#192]
Currently we do not support helm charts for RMS/CreditCardApplication/TEA image types. Kindly provide support for the same.

**Comment by LakshmiMekala** [comment]
Required code changes are made available in PR #194

**Comment by rameshpolishetti** [comment]
@AdittyThakare This is made available in PR #213 since the previous PR got dropped.

Also, note that RMS deployments got merged into the same be-helm chart since RMS is also a BE app. But it is not the case for TEA. Hence TEA will continue to have separate configurations.

**Comment by AdittyThakare** [comment]
RMS deployment has got merged with BE helm chart now. 

On AWS EKS for single RMS replica have tested with following configurations:
- Ignite_Ignite_None
- Ignite_Ignite_SN
- Ignite_Ignite_Cassandra
- Ignite_Ignite_RDBMS(Mysql)
- AS2_AS2_None
- AS2_AS2_SN
- AS2_AS2_RDBMS(Mysql)
- FTL_Ignite_None
- FTL_Ignite_Cassandra
- FTL_Ignite_SN
- FTL_Ignite_Mysql
- FTL_Ignite_AS4
- Ignite_Ignite_AS4
- FTL_AS4

Basic single RMS replica flows have been tested on AWS Fargate and Azure as well.

Testing related to multiple replica is pending as NPE issue is observed. Issue https://github.com/TIBCOSoftware/be-tools/issues/197 is open for the same.
