### ISSUE TITLE
Build application image without mutlistage builds

### ISSUE THREAD

**Issue by vsirimalla** [TIBCOSoftware/be-tools#193]
### Version Information
| Software       | Version(s)     |
| -------------- | -------------- |
| BusinessEvents |     5.6.1      |
| OS Type?       |    RHEL        |
| OS Version?    |    7.9         |
| Docker         |      V1.13     |
| Kubernetes     |                |
| Helm           |                |

### What is the expected behavior?
We are use Docker that's shipped with RHEL. and this Docker does not support multi stage builds through Dockerfile.
We need alternative scripts to create the application image without using Multistage builds.

### What is the actual behavior?
build_image.sh is trying to build through Multistage build.

### Please provide a unit test that demonstrates the bug.
Build the application image on RHEL Server, installing RedHat's Docker through YUM.

### Any possible solutions?
We need alternative scripts to create the application image without using Multistage builds.

### Can you identify the location in the source code where the problem exists?
Dockerfile

### If the bug is confirmed, would you be willing to submit a PR?
Yes / No _(Help can be provided if you need assistance submitting a PR)_

**Comment by nareshkumarthota** [comment]
Can you try with `buildah` tool instead of `docker`.

Steps:
1. Install `buildah` tool from [here](https://github.com/containers/buildah/blob/master/install.md#rhel7).
2. Pull the master scripts from be-tools repo
3. Try executing build script with `-b` argument.
```sh
./build_image.sh -i app -s <installer-location> -b buildah -t imagename:v1
```

**Comment by vsirimalla** [comment]
I tried and got `User namespaces are not enabled in /proc/sys/user/max_user_namespaces.`
Also, we may not able to install tools like `buildah `on our enterprise jenkins Servers for the security reasons.

Could you please help with alternatives scripts leverage existing Docker installation  on RHEL?

I did try the following and got partial success.
1) I have two different Dockerfiles, with the first Dockerfile, I have just created the BusinessEvents Base Image. (where its installing AS, BE)
2) Started a container of above BE Baseimage, and while the container is running, I copied out the files from container
`/tibco_home` and `/home/tibco/be`  using `docker cp .....` and discarded image and container.

and we are still optimizing the size of the image this way.

3) I have used the directories extracted from step 2, and COPY them into Application Image with another Dockerfile that's resuming  the build of the application image.


Doing this way, I think we might save time on the repeating task of creating task 1 and 2.
As the application code changes in BE project, we would have just execute step 3 to create a fresh application image.

Please share your thoughts.

**Comment by nareshkumarthota** [comment]
We already have option to avoid repeated installation for each build. This is achieved if we use `image_type` as `s2ibuilder`.
First you need to create base image by passing `-i` as `s2ibuilder` with all required installers later with help of `s2i` tool you can recreate application image by passing application artefacts. Complete information is available in [wiki](https://github.com/TIBCOSoftware/be-tools/wiki/Building-TIBCO-BusinessEvents-Application-Docker-Image#method-two---building-using-source-to-image-s2i-toolkit). 

This also requires multistage build. You can try upgrading docker version. If upgrading is not feasible, The idea which you have mentioned also works. But need to be tested thoroughly.

**Comment by rameshpolishetti** [comment]
@vsirimalla Red Hat Enterprise Linux offers a set of container tools (`buildah`, `podman`, etc...) to work directly with Linux containers and container images that require no container engine or docker commands or services. Refer: [RHEL docs](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux_atomic_host/7/html/managing_containers/finding_running_and_building_containers_with_podman_skopeo_and_buildah#building_container_images_with_buildah)

Now `be-tools` also supports building OCI compatible container image using `buildah` tool in addition to `docker`.

You may try installing `buildah` by referring to section 1.6.2 of [RHEL docs](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux_atomic_host/7/html/managing_containers/finding_running_and_building_containers_with_podman_skopeo_and_buildah#building_container_images_with_buildah)

```sh
# subscription-manager repos --enable=rhel-7-server-rpms
# subscription-manager repos --enable=rhel-7-server-extras-rpms
# yum -y install buildah
```

**Comment by rameshpolishetti** [comment]
Hi @vsirimalla, Just wanted to check whether you are able to use `buildah` to build BE application container image?

**Comment by vsirimalla** [comment]
hi @rameshpolishetti 
Sorry for the delay in response.

we had to park this because of few other commitments. Now we are back looking at this BE Docker image.

so, we could not use buildAh, since its not approved in our Org.
Instead, this is what I did
1) Split Docker image build into two parts
   first part is  just to build a BE Software image with Custom GV lookup framework. (using software installer archives .zip)
   
   and then I manually ran a temporary container using above image, and using `docker cp`, pulled out "/home/tibco/be" and "/tibco_home" which as you know are the only two things that application Image cares about.
   
   2) As part of the second part of building the image i.e. Application Image (with another Dockerfile)
     I have copied directories (be and tibco_home) into the Docker image, modified build_image.sh a bit
     
     And got the application image created successfully.
     
     I am planning to reuse the "be" and "tibco_home" directories for the application image build as we keep getting upgraded EAR or CDD. This way we could save time having to rebuild the first part of the image build i.e BE Software image. And we could rebuild software image again, and follow step 1) only when we want to upgrade BE Software versions.
  
To automate the build process,  I will have to write jenkins job to just build the application image based out of these directories I pulled off Software image.
  
     
     
     And I tested, Application is able to start just fine.
     Only thing,  that's concerning me was, the permissions in the images are kind of looks bad, everything is showing just ??????? 
     is that expected, or does it impacts/impairs the application running inside the container in anyway?

**Comment by rameshpolishetti** [comment]
Hi @vsirimalla folder permissions "???????" is not expected, this may cause undesired runtime behavior.
I suspect that original file permission information is getting lost while copying from _container1 -> local file system -> final container image_. You can update file permission to desired level (same as Docker image - part one) using `chmod` after copying files from location system -> final container.

**Comment by vpatil-tibco** [comment]
Details provided. Hopefully that has solved the issue. If you continue to face the issue, please reopen and provide necessary details, else log a separate issue.
