### ISSUE TITLE
If storageClass name is provided in values.yaml, generated pvc still shows storageclass as ""

### ISSUE THREAD

**Issue by jgirase** [TIBCOSoftware/be-tools#200]
In values.yaml, provide storageclass name as efs-sc as below,

volumes:
  #Required for sharednothing and store in all cloud providers
  pvProvisioningMode: dynamic                 # Default set to dynamic, For aws eks(dynamic or static) and fargate set to `static`, and 
  storageClass: efs-sc                 #Use one of the available storage classes as per your preference, for aws cluster with  `pvProvisioningMode:dynamic` efs file system it creates a new storageclass, for `pvProvisioningMode:static` leave the storageclass field empty
  snclaimVolume: pv0003

Generate yaml files using dry-run , it shows storageclass as empty so the one user provided not used anywhere.

# Source: BE Helm Chart/templates/rms-pvc.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "rms-sn-rms-pvc-webstudio"
spec:  
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 0.5Gi
---
# Source: BE Helm Chart/templates/rms-pvc.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "rms-sn-rms-pvc-shared"
spec:  
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 0.5Gi
---
# Source: BE Helm Chart/templates/rms-pvc.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "rms-sn-rms-pvc-store"
spec:
  storageClassName: ""
  accessModes: 
    - ReadWriteMany
  resources:
    requests:
      storage: 0.5Gi
---
# Source: BE Helm Chart/templates/rms-pvc.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "rms-sn-rms-pvc-applog"
spec:
  storageClassName: ""
  accessModes: 
    - ReadWriteMany
  resources:
    requests:
      storage: 0.5Gi
---

**Comment by LakshmiMekala** [comment]
This is expected for pvProvisioningMode:static, eks fargate and eks cluster do not require any storageclass, User need to create required directories as per the requirement, inside efs file system like: data-store,logs etc,

This is not an issue

**Comment by jgirase** [comment]
This has been observed for pvProvisioningMode: dynamic
let us know if its expected?

**Comment by LakshmiMekala** [comment]
When pvProvisioningMode: dynamic, storageClass: set to empty, be helm deployment will create a storageclass with prefixing releasename(<releasename>-be-sc).

**Comment by LakshmiMekala** [comment]
There is an issue with cpType=aws,pvProvisioningMode: dynamic, storageClass: set to empty. Fixed the issue in PR #194

**Comment by jgirase** [comment]
Its working as expected with latest changes available in branch feature-rms-helm.
Find attached logs for reference.
[rms-dynamic.log](https://github.com/TIBCOSoftware/be-tools/files/6574796/rms-dynamic.log)
