### ISSUE TITLE
When RMS is configured with persistence SharedNothing , helm delete/recreate with same release name does not persist data

### ISSUE THREAD

**Issue by jgirase** [TIBCOSoftware/be-tools#201]
Prerequisite:
1.EKS cluster running with efs csi driver provisioning 
2.ECR should have RMS/CCA images with configurations as Ignite + Ignite +Shared Nothing
3.EFS file system created in same vpc as eks cluster

Steps:
1.Update values.yaml as per required configuration shared nothing
2.Keep storageclass empty so that it will be generated using release name with provisioning mode as dynamic
3.Deploy applications using helm for example : helm install rms-sn .
4.Make sure all pods are running for rms as well as cca application
5.Copy data from local machine to RMS pod volume mounts like webstudio/security/notify
6.Login to RMS server and checkout cca project 
7.Perform steps mentioned in cca.readme file to create artifacts and hot deploy them as well
8.Delete deployment using helm: helm delete rms-sn
9.All pods are deleted with rms related pvc 
10.Now deploy applications again with same release name : helm install rms-sn .
11.Data copied inside volume mounts is not present in rms pod though its available on efs file system
12.Also the rms state is not persisted as the changes done before deleting deployment are not available in webstudio

 Kindly let us know if this design is intentional or a configuration is wrong at our side
 
Note: This works fine with static mode of pv provisioning for EKS cluster. Issue arises when pv provisioning mode is dynamic based on storage class

**Comment by jgirase** [comment]
@vpatil-tibco For volumes like shared nothing data store and logs with respect to RMS deployment , I think we need to persist the data across helm install/uninstall of same release to maintain the state of RMS lifecycle. However, data present on other volumes like security/notify/share/webstudio I am not sure do we really need to persist it or not post helm uninstall so it would be helpful if you can suggest on this.

**Comment by LakshmiMekala** [comment]
Fixed with PR #194

**Comment by vpatil-tibco** [comment]
Agree, datastore is mandatory, it needs to exists outside of the lifecycle of rms service. Logs, security and shared folders can be optional. I feel its best for the end user to have this option, if they want to maintain these across RMS service lifecycle then, they should configure them as static PV's else continue with default dynamic PV's.

**Comment by jgirase** [comment]
@vpatil-tibco We tried following use case with existing scripts where store and logs volumes are persisted for RMS deployment.
We found inconsistent behaviour with respect to project artifacts as "shared" and "webstudio" volumes are not persisted with current setup post uninstall of helm release.
Tested RMS with SN persistence in case of dynamic PV's. There are some inconsistencies in UI and actual rms repository after the release is uninstalled and then re-installed. Below are the steps followed:
1. Install helm release with RMS_SN persistence. Copy shared, WebStudio, security and notify folders.
2. Login to WebStudio. Creat RTI1, RTI2. Commit, Approve and hot deploy both RTIs
3. Create RTI3, Commit it
4. Create RTI4. Do not commit it
5. Now uninstall helm release
6. Install helm release again
7. Copy shared, WebStudio, security and notify folder
8. Login to WebStudio. Here, you can see previously checked out project, hot deployed artifacts, artifact in the worklist pending for approval.
Couple of things here:
a) RTI1 and RTI2 are visible in the workspace in#8 but those are not present in the file system repo(root directory) as it was deleted when the release was uninstalled. So there is inconsistency in the WebStudio UI and the actual file repository
b) If we try to deploy RTI1 and RTI2 from UI again, it shows artifact is already undeployed(as it doesnt exists in shared folder and WebStudio/CreditCardApplication/Rule_Templates folders)

So from the above observations it looks like either we have to persist "shared" as well as "webstudio" volumes in case of dynamic provisioning for RMS deployment or we can recommend static provisioning only in case of RMS needs to configure with any persistence options like SN/RDBMS/Store.

Kindly provide your feedback.

**Comment by vpatil-tibco** [comment]
Yes, we will have to do. Will need to persist, shared, WebStudio as well as security. Notifications need not be.
@LakshmiMekala Let's discuss this tomorrow if you have questions.

**Comment by LakshmiMekala** [comment]
I have included required code changes to this issue, 

For pvProvisioningType: dynamic, rms pvc's will be provisioned dynamically(similar to sharednothing for BE APP),rms now persists data for shared, webstudio, security and notify. 

For pvProvisioningType: static(currently support only for aws), rms pvc's and pv's will be created from `helm install` and gets deleted after `helm delete` 

Fix is available in PR #194

**Comment by jgirase** [comment]
With the latest scripts available in branch feature-rms-helm , RMS configured with SN is working fine post helm uninstall as well.
Find attached logs for reference.
[RMS_SN_EKS_dynamic_provisioning_logs.zip](https://github.com/TIBCOSoftware/be-tools/files/6623101/RMS_SN_EKS_dynamic_provisioning_logs.zip)
