### ISSUE TITLE
RMS engine log file name is not consistent with application when logs are mounted

### ISSUE THREAD

**Issue by jgirase** [TIBCOSoftware/be-tools#202]
When mountLogs is enabled , it saves log to store. So when RMS along with Creditcardapplication is deployed  to EKS cluster , log files are saved to EFS. Application like CCA log files are persisted with prefix  helm release name however same is not applied to RMS logs.
Kindly make it consistent for RMS as well as Application deployments.
Please refer below log files listed on EFS ,

[ec2-user@ip-192-168-16-62 applog]$ ls
be-engine-ignite.log               fdsn-static-becacheagent-1-as.log      rms-static-becacheagent-0-ignite.log  rms-static-beinferenceagent-0-ignite.log
be-engine.log                      fdsn-static-becacheagent-1.log         rms-static-becacheagent-0.log         rms-static-beinferenceagent-0.log
fdsn-static-becacheagent-0-as.log  fdsn-static-beinferenceagent-0-as.log  rms-static-becacheagent-1-ignite.log
fdsn-static-becacheagent-0.log     fdsn-static-beinferenceagent-0.log     rms-static-becacheagent-1.log

**Comment by LakshmiMekala** [comment]
Fixed with PR #194

**Comment by jgirase** [comment]
Its fixed now. Verified on branch feature-rms-helm
Find below logs for reference
[ec2-user@ip-192-168-16-62 rms-applog]$ ls
rms-static-rms-0-ignite.log  rms-static-rms-0.log
