### ISSUE TITLE
Distribute BE instances (pods) evenly across available nodes

### ISSUE THREAD

**Issue by rameshpolishetti** [TIBCOSoftware/be-tools#204]
**Context**
Enable Kubernetes native `pod affinity` functionality through BE helm chart, so that the BE instances (pods) distribute evenly across available nodes (physical boxes).

**Alternatives**
No

**Has the feature been requested before?**
No

**If the feature request is approved, would you be willing to submit a PR?**
Yes

**Comment by LakshmiMekala** [comment]
Required implementation is completed and available with PR #194

**Comment by rameshpolishetti** [comment]
This is made available in PR #213 since previous PR got dropped.

**Comment by tsaxena18** [comment]
Tried with setting it to true. As per definition of podAntiAffinity, no two pods can be on same node as per defined rule. Here it does not seem to be working for me as per my understanding. I will continue to debug more into it.
[apps@tsaxena-z820 kubernetes]$ kubectl get pods -o wide
NAME                     READY   STATUS    RESTARTS   AGE     IP               NODE                                           NOMINATED NODE   READINESS GATES
ccapp-cacheagent-0       1/1     Running   0          4m35s   192.168.44.232   ip-192-168-33-68.us-east-2.compute.internal    <none>           <none>
**ccapp-cacheagent-1**       1/1     Running   0          4m34s   192.168.26.82    ip-192-168-1-38.us-east-2.compute.internal     <none>           <none>
**ccapp-cacheagent-2**       1/1     Running   0          4m31s   192.168.71.5     ip-192-168-85-167.us-east-2.compute.internal   <none>           <none>
ccapp-cacheagent-3       1/1     Running   0          4m28s   192.168.41.254   ip-192-168-35-250.us-east-2.compute.internal   <none>           <none>
**ccapp-cacheagent-4**       1/1     Running   0          4m26s   192.168.3.182    ip-192-168-1-38.us-east-2.compute.internal     <none>           <none>
**ccapp-cacheagent-5**       1/1     Running   0          4m24s   192.168.74.112   ip-192-168-85-167.us-east-2.compute.internal   <none>           <none>
ccapp-inferenceagent-0   1/1     Running   0          4m35s   192.168.78.132   ip-192-168-85-167.us-east-2.compute.internal   <none>           <none>

**Comment by LakshmiMekala** [comment]
@tsaxena18 this feature defines pods are evenly distributed across nodes. The above mentioned output of nodes is correct

**Comment by tsaxena18** [comment]
There are two types of node affinity, called requiredDuringSchedulingIgnoredDuringExecution and preferredDuringSchedulingIgnoredDuringExecution and they are like hard/soft rule as mentioned in https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/.

Currently, I can see the latter, preferredDuringSchedulingIgnoredDuringExecution, is defined in our helm script and if I change it to other one, then install throws error so I assume we have to stick with this option only.
Closing this ticket as the behavior is expected as per rule defined in script.

Let me know if we need to create a ticket to support other type, i.e, requiredDuringSchedulingIgnoredDuringExecution.

**Comment by LakshmiMekala** [comment]
@tsaxena18 we are aware of this features wrt podAntiAffinity, we have requirement to distribute pods across nodes evenly. U can good to close this issue. I dont think it is required to create a new support ticket for other type

**Comment by LakshmiMekala** [comment]
Closing as per @tsaxena18 comments
