### ISSUE TITLE
The information about supplied arguments in image creation are not consistent across platforms.

### ISSUE THREAD

**Issue by vivekshende** [TIBCOSoftware/be-tools#21]
The information that is listed out about supplied arguments are not consistent across platforms (win, linux). There are few parameters in linux which are missing and some information is not consistent with the way it is displayed on windows.
Look at the output of build app utility for win and linux as shown below :

C:\Share\BE_560_V80\be\5.6\cloud\docker\bin>build_app_image.bat -l E:\v80 -a E:\Work_560\temp-new\SN -r fdsn:v80
INFO: Supplied Arguments
----------------------------------------------
INFO: Installers Location - E:\v80
INFO: Ear/Application Location - E:\Work_560\temp-new\SN
INFO: Image Repo - fdsn:v80
----------------------------------------------
----------------------------------------------
INFO: Dockerfile - Dockerfile.win
INFO: Installers Platform - win
INFO: BusinessEvents Hf - na
INFO: Addons - views,process,
INFO: ActiveSpaces version - 2.4.0
INFO: ActiveSpaces Hf - 002
INFO: CDD file name - fdstore.cdd
INFO: EAR file name - fdstore.ear
----------------------------------------------

[apps@beqacentosz820 bin]$ ./build_app_image.sh -l /home/apps/Installers/BE/560/v82 -a /home/apps/Testing/temp560N/None -r fdc:v82
INFO:Supplied Arguments :
----------------------------------------------
INFO:VERSION : 5.6.0
INFO:EDITION : enterprise
INFO:INSTALLER DIRECTORY : /home/apps/Installers/BE/560/v82
INFO:APPLOCATION Data DIRECTORY : /home/apps/Testing/temp560N/None
INFO:ADDONS : process,views
INFO:DOCKERFILE : Dockerfile
INFO:HF : na
INFO:AS-HF : 002
INFO:IMAGE VERSION :

**Comment by nareshkumarthota** [comment]
This is taken care in improvements branch `docker-scripts-improvements`.

**Comment by ykalidin** [comment]
Working as expected.The information about supplied arguments is same in linux and windows.

**Comment by tsaxena18** [comment]
Verified for Windows and Linux platforms. The information of arguments is same as expected.

**For Linux** -->
[apps@beqacentos7 docker]$ ./build_image.sh -i app -a /home/apps/Testing/temp610/None-Iginte -s /home/apps/Installers/BE/610 -t fdci:610

INFO: Supplied/Derived Data:

INFO: INSTALLER DIRECTORY          : [/home/apps/Installers/BE/610]
INFO: APPLICATION DATA DIRECTORY   : [/home/apps/Testing/temp610/None-Iginte]
INFO: BE VERSION                   : [6.1.0]
INFO: BE ADDONS                    : [process]
INFO: AS LEGACY VERSION            : [2.4.1]
INFO: FTL VERSION                  : [6.5.0]
INFO: AS VERSION                   : [4.5.0]
INFO: CDD FILE NAME                : [IgniteClusterDeploy.cdd]
INFO: EAR FILE NAME                : [fdcache.ear]
INFO: DOCKERFILE                   : [./dockerfiles/Dockerfile]
INFO: IMAGE TAG                    : [fdci:610]
INFO: JRE VERSION                  : [11]

WARN: The directory: [/home/apps/Installers/BE/610] contains both FTL and Activespaces(legacy) installers. Removing unused installer improves the docker image size.

**For Windows** -->
C:\Share\be-tools-docker-scripts-improvements\cloud\docker>build_image.bat -i app -a C:\Share\Work_610\temp -s C:\Share\Installers\610\v64 -t fdci:v64

INFO: Supplied/Derived Data:

INFO: INSTALLER DIRECTORY          : [C:\Share\Installers\610\v64]
INFO: APPLICATION DATA DIRECTORY   : [C:\Share\Work_610\temp]
INFO: BE VERSION                   : [6.1.0]
INFO: BE ADDONS                    : [process]
INFO: AS LEGACY VERSION            : [2.4.1]
INFO: FTL VERSION                  : [6.5.0]
INFO: AS VERSION                   : [4.5.0]
INFO: CDD FILE NAME                : [IgniteClusterDeploy.cdd]
INFO: EAR FILE NAME                : [fdcache.ear]
INFO: DOCKERFILE                   : [.\dockerfiles\Dockerfile.win]
INFO: IMAGE TAG                    : [fdci:v64]
INFO: JRE VERSION                  : [11]

WARN: The directory: [C:\Share\Installers\610\v64] contains both FTL and Activespaces(legacy) installers. Removing unused installer improves the docker image size.

**Comment by rameshpolishetti** [comment]
Closing the issue as it is validated succesfully.
