### ISSUE TITLE
Cannot change Version name for mount in berms.yaml file

### ISSUE THREAD

**Issue by rafisolutions** [TIBCOSoftware/be-tools#210]
### Version Information
| Software       | Version(s)     |
| -------------- | -------------- |
| BusinessEvents |     6.1           |
| OS Type?       |         Ubuntu       |
| OS Version?    |                |
| Docker         |                |
| Kubernetes     |                |
| Helm           |                |

### What is the expected behavior?  
Trying to change the version in the moiunt path for security to 6.1. When we launch the RMS ,the security folder is empty and cannot login into webstudio application. 
Created docker image by pointing to the installables of BE enterprise edition 6.1 version.

volumeMounts:        - mountPath: "/opt/tibco/be/**5.6**/rms/shared/"          name: shared        - mountPath: "/opt/tibco/be/5.6/rms/config/**security**/"          name: security        - mountPath: "/opt/tibco/be/5.6/examples/standard/WebStudio/"          name: webstudio        - mountPath: "/opt/tibco/be/5.6/rms/config/notify/"          name: notify

### If the bug is confirmed, would you be willing to submit a PR?
Yes / No _(Help can be provided if you need assistance submitting a PR)_

**Comment by rameshpolishetti** [comment]
@rafisolutions I assume you are trying to deploy a **BE** app using the **helm** chart available in the branch [feature-rms-helm](https://github.com/TIBCOSoftware/be-tools/tree/feature-rms-helm).

Please make sure that **values.yaml (rms. beVersion: 6.1)** is updated correctly with the desired **BE** version.

**Comment by rafisolutions** [comment]
Hi Ramesh

We are not using helm chart. We are using individual yaml files only.

Rafi

**Comment by rameshpolishetti** [comment]
Hi @rafisolutions 
The security folder is empty which means - The file system which got mounted to the RMS pod is empty.
You need to copy/pre-fill required RMS artifacts (security & WebStudio contents) into the filesystem and then launch the RMS pod again.

**Comment by rameshpolishetti** [comment]
Hi @rafisolutions Not heard from you since my previous comment. Please let me know if you are looking for any further information in this regard.

**Comment by vpatil-tibco** [comment]
@rafisolutions - If you follow the documentation, it outlines the step of copying the necessary folder contents into the mounted PV's.
(Step 9) - https://github.com/TIBCOSoftware/be-tools/wiki/Running-on-RMS

I think that is what is missing at your end.

**Comment by vpatil-tibco** [comment]
The above step seems to have solved the issue. Closing this issue. If you continue facing the same issue, please reopen or log a separate issue.
