### ISSUE TITLE
Add support to load GVs from ConfigMap and Secrets

### ISSUE THREAD

**Issue by rameshpolishetti** [TIBCOSoftware/be-tools#212]
**Context**
In the current BE Helm chart, there is no support to supply extra environment variables / BE Global Variables using Kubernetes ConfigMaps OR Secrets. Adding this support enables the user to inject application-specific configurations easily.

**Alternatives**
Need to use GV framework.

**Has the feature been requested before?**
NO

**If the feature request is approved, would you be willing to submit a PR?**
Yes

**Comment by rameshpolishetti** [comment]
This feature is available at: https://github.com/TIBCOSoftware/be-tools/tree/feature-helm-deploy-rms

**Comment by priyanka-nawal** [comment]
Verified GV using config map by creating configMap for MySQL credentials like URL,DriverName, Username and password.
Also verified loading GVs from secret by creating secret for Cassandra username and password
Attaching logs for reference.
[logs.zip](https://github.com/TIBCOSoftware/be-tools/files/6791735/logs.zip)

**Comment by rameshpolishetti** [comment]
Thank you @priyanka-nawal. Closing the issue as it is successfully verified.
