### ISSUE TITLE
Incorrect value for rmsDeployment getting printed on console while installing helm release

### ISSUE THREAD

**Issue by priyanka-nawal** [TIBCOSoftware/be-tools#214]
Set rmsDeployment: true in the yaml file and install the release. Below information gets printed on console. In the output, it says 'This is RMS deployment' and value is 'no'. Ideally it should be yes when rmsDeployment: true.

`C:\be-tools1\be-tools-feature-helm-deploy-rms\cloud\kubernetes>helm install ignite-mysql-v6 ./helm -f ./helm/values_ignite_ignite_mysql_v2.yaml
NAME: ignite-mysql-v6
LAST DEPLOYED: Wed Jun 30 13:46:33 2021
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
Thank you for using BE Helm Chart.

TIBCO BusinessEvents application has been deployed with the following details:

Release name:              ignite-mysql-v6
Cloud provider:            aws
Cluster provider:          ignite
Hot deployments:           not enabled
This is a RMS deployment:  no

Following services have been exposed for external access:

  Service name: ignite-mysql-v6-rmsagent-httpchannel
    To connect to this service from outside the cluster, use below details:
    echo NODE_IP: $(kubectl get nodes -o jsonpath="{.items[0].status.addresses[0].address}")
    echo NODE_PORT: $(kubectl get -o jsonpath="{.spec.ports[0].nodePort}" services ignite-mysql-v6-rmsagent-httpchannel)`

**Comment by rameshpolishetti** [comment]
@priyanka-nawal it is fixed. Please take latest changes from the branch/feature-helm-deploy-rms

**Comment by priyanka-nawal** [comment]
Now proper flag value is getting printed on console. Attached output of rms and cca release installation.

[Issue_214.txt](https://github.com/TIBCOSoftware/be-tools/files/6770128/Issue_214.txt)
[Issue_214_CCA.txt](https://github.com/TIBCOSoftware/be-tools/files/6770129/Issue_214_CCA.txt)
