### ISSUE TITLE
Helm : EKS Fargate - MySql pod is not starting and stuck at pending state when persistence is enabled.

### ISSUE THREAD

**Issue by tsaxena18** [TIBCOSoftware/be-tools#217]
### Version Information
| Software       | Version(s)     |
| -------------- | -------------- |
| BusinessEvents |       6.1.1         |
| OS Type?       |        Linux        |
| OS Version?    |     CentOS Linux release 7.9           |
| Docker         |     20.10.7           |
| Kubernetes     |   1.21.1             |
| Helm           |   3.5.4             |

### What is the expected behavior?
MySql pod should start using Helm EKS fargate deployment.

### What is the actual behavior?
MySql pod is not starting and stuck at pending state when myql persistence is enabled. The describe pod says that, "Pod not supported on Fargate: volumes not supported: data not supported because: PVC data-rmsapp-mysql-0" not bound, as described below :

[apps@tsaxena-z820 kubernetes]$ kubectl describe pod rmsapp-mysql-0
Name:                 rmsapp-mysql-0
Namespace:            default
Priority:             2000001000
Priority Class Name:  system-node-critical
Node:                 <none>
Labels:               app.kubernetes.io/component=primary
                      app.kubernetes.io/instance=rmsapp
                      app.kubernetes.io/managed-by=Helm
                      app.kubernetes.io/name=mysql
                      controller-revision-hash=rmsapp-mysql-7854598dd8
                      eks.amazonaws.com/fargate-profile=fp-default
                      helm.sh/chart=mysql-8.2.3
                      statefulset.kubernetes.io/pod-name=rmsapp-mysql-0
Annotations:          checksum/configuration: 704f7df92af430ae68e0ce0b0995f55c7c26a685ba2e4ac818ced3951bc66aed
                      kubernetes.io/psp: eks.privileged
Status:               Pending
IP:
IPs:                  <none>
Controlled By:        StatefulSet/rmsapp-mysql
Containers:
  mysql:
    Image:      docker.io/mysql:5.7
    Port:       3306/TCP
    Host Port:  0/TCP
    Args:
      --lower_case_table_names=1
      --sql_mode=IGNORE_SPACE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
    Liveness:  exec [/bin/bash -ec password_aux="${MYSQL_ROOT_PASSWORD:-}"
if [[ -f "${MYSQL_ROOT_PASSWORD_FILE:-}" ]]; then
    password_aux=$(cat "$MYSQL_ROOT_PASSWORD_FILE")
fi
mysqladmin status -uroot -p"${password_aux}"
] delay=120s timeout=1s period=10s #success=1 #failure=3
    Readiness:  exec [/bin/bash -ec password_aux="${MYSQL_ROOT_PASSWORD:-}"
if [[ -f "${MYSQL_ROOT_PASSWORD_FILE:-}" ]]; then
    password_aux=$(cat "$MYSQL_ROOT_PASSWORD_FILE")
fi
mysqladmin status -uroot -p"${password_aux}"
] delay=30s timeout=1s period=10s #success=1 #failure=3
    Environment:
      BITNAMI_DEBUG:        false
      MYSQL_ROOT_PASSWORD:  <set to the key 'mysql-root-password' in secret 'rmsapp-mysql'>  Optional: false
      MYSQL_DATABASE:       BE_DATABASE
    Mounts:
      /bitnami/mysql from data (rw)
      /opt/bitnami/mysql/conf/my.cnf from config (rw,path="my.cnf")
      /var/run/secrets/kubernetes.io/serviceaccount from rmsapp-mysql-token-pt47n (ro)
Conditions:
  Type           Status
  PodScheduled   False
Volumes:
  data:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  data-rmsapp-mysql-0
    ReadOnly:   false
  config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      rmsapp-mysql
    Optional:  false
  rmsapp-mysql-token-pt47n:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  rmsapp-mysql-token-pt47n
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason            Age   From               Message
  ----     ------            ----  ----               -------
  Warning  FailedScheduling  19m   fargate-scheduler  Pod not supported on Fargate: volumes not supported: data not supported because: PVC data-rmsapp-mysql-0 not bound

### Please provide a unit test that demonstrates the bug.
1. Create EKS cluster of type fargate. 
2. Setup helm yaml files acc. with appropriate values. Set mysql=true and enable its persistence.

**Comment by rameshpolishetti** [comment]
@tsaxena18 I see that mysql pod is pending in status because corresponding PV/PVCs are not available.

AWS Fargate only supports static provisioning that means PV, PVC need to be created manually (Ref: https://docs.aws.amazon.com/eks/latest/userguide/efs-csi.html under consideration point 1)

Pre create required PV/PVCs manually should fix the issue.

**Comment by rameshpolishetti** [comment]
Note: Since mysql is a sub chart, BE chart does not create any PV/PVCs for for mysql.

**Comment by tsaxena18** [comment]
Closing as per the comments.
