### ISSUE TITLE
OpenJDK support for BE application container image

### ISSUE THREAD

**Issue by rameshpolishetti** [TIBCOSoftware/be-tools#218]
**Context**
Currently there is no option to use [open-jdk](https://jdk.java.net/) in the place of TIBCO JDK (which comes along with `TIBCO BusinessEvents` installation) while creating BE container image.

**Alternatives**
No

**Has the feature been requested before?**
NA

**If the feature request is approved, would you be willing to submit a PR?**
Yes

**Comment by nareshkumarthota** [comment]
This feature is available in branch `feature-openjdk`.

**Comment by rameshpolishetti** [comment]
This can be validated on master branch.

**Comment by athombare** [comment]
Verified the newly introduced support of openJDK in place of TIBCO JRE with BE container image.

openJDK version used for testing - openjdk-11+28 (Oracle Open JDK)

`2021 Aug 16 21:48:46.706 GMT +05:30 be-engine INFO [main] - [user] [inference-class] ************* Java version: 11+28
2021 Aug 16 21:48:46.706 GMT +05:30 be-engine INFO [main] - [user] [inference-class] ************* Java vendor: Oracle Corporation
2021 Aug 16 21:48:46.706 GMT +05:30 be-engine INFO [main] - [user] [inference-class] ************* Java name: OpenJDK Runtime Environment`

Verified the -o flag with positive as well as negative scenarios successfully.

e.g
-o is provided and openjdk installer not present
-o is provided and openjdk installer present
-o is not provided and openjdk installer present

Verified Image build and run of all supported types i.e app, rms and teagent.

Verified Image build and run for all supported platforms (Windows with Windows Installers, Windows Installation and Linux Installers / Linux with Linux Installers and Linux Installation / Mac with Linux Installers) however in-depth testing has been done on linux platform only.

Also tested image push and run on AWS Kubernetis.

Attached excel file with all tested flows as well as logs for reference.

[Github OpenJDK.xlsx](https://github.com/TIBCOSoftware/be-tools/files/7109670/Github.OpenJDK.xlsx)
[OpenJDK_218_Logs.zip](https://github.com/TIBCOSoftware/be-tools/files/7109671/OpenJDK_218_Logs.zip)

**Comment by rameshpolishetti** [comment]
Thank you @athombare. Closing the issue as it is successfully verified.
