### ISSUE TITLE
Integrate fromInstall scripts into base docker scripts

### ISSUE THREAD

**Issue by vivekshende** [TIBCOSoftware/be-tools#22]
As part of 5.6, we combined multiple docker scripts into single script. However we missed adding "fromInstall" option to it. Which we included later a separate set.

Ideally we should simply have an argument to the base docker script to accept "fromInstall" option.

**Comment by nareshkumarthota** [comment]
Multiple docker scripts combined into single script `build_image`. This script is used to create all types of images. Changes made available in branch `docker-scripts-improvements`

**Comment by ykalidin** [comment]
Script build_image has the source option which determines to build image using installer or frominstall option.Working as expected.

**Comment by jgirase** [comment]
Now single docker image build script works for fromInstallation as well as fromInstallers.

**Comment by rameshpolishetti** [comment]
Closing the issue as it is validated successfully.
