### ISSUE TITLE
TEA Agent for BE not working in AWS ECS environment

### ISSUE THREAD

**Issue by rameshpolishetti** [TIBCOSoftware/be-tools#220]
### Version Information
| Software       | Version(s)     |
| -------------- | -------------- |
| BusinessEvents | 6.1.1               |
| OS Type?       | Ubuntu               |
| OS Version?    | 20.04               |
| Docker         |  20.10              |
| Environment     | AWS ECS   |

### What is the expected behavior?
When running TEA Agent for BE on AWS ECS environment, it should get registered automatically on TEA server and show all BE instances running the same ECS environment.

### What is the actual behavior?
TEA Agent for BE is starting successfully but not getting registered with TEA server.

### Any possible solutions?
Scripts located at `/cloud/docker/lib/*.py` which are used to detect instances running in the ECS environment seems to be out dated. Updating these scripts should resolve the issue.

**Comment by nareshkumarthota** [comment]
Fixed and pushed to master.
