### ISSUE TITLE
Use GitHub Actions to automate helm template tests on new PR

### ISSUE THREAD

**Issue by rameshpolishetti** [TIBCOSoftware/be-tools#222]
**Context**
Automate running helm template tests on a new pull request on to `master` branch using `GitHub Actions`

**Alternatives**
NA

**Has the feature been requested before?**
NA

**If the feature request is approved, would you be willing to submit a PR?**
Yes

**Comment by LakshmiMekala** [comment]
Implemented Github actions CI workflow with PR #221
