### ISSUE TITLE
Unused artifacts are getting copied while building RMS image from local installation

### ISSUE THREAD

**Issue by LakshmiMekala** [TIBCOSoftware/be-tools#225]
### Version Information
| Software       | Version(s)     |
| -------------- | -------------- |
| BusinessEvents |    6.1            |
| OS Type?       |      Linux          |
| OS Version?    |       20.04         |
| Docker         |            20.10.2    |
| Kubernetes     |                |
| Helm           |                |

### What is the expected behavior?
For default rms.cdd , as2 artifacts need not required to copy, applies to ftl cdd as well
### What is the actual behavior?
Have as2 and BE installed, where as2 home is autoset in be-engine.tra
Trying to create default RMS image using './build_image.sh -i rms -s $BE_HOME', as2 artifacts are getting copied to default ignite rms.cdd, applicable for ignite and ftl, 
1. Copying required dependencies is meaningful
2. With unwanted dependencies ideally increase image size

### If the bug is confirmed, would you be willing to submit a PR?
Yes / No _(Help can be provided if you need assistance submitting a PR)_

**Comment by nareshkumarthota** [comment]
Kindly check the documentation (here)[https://github.com/TIBCOSoftware/be-tools/wiki/Before-You-Begin].
It is intended behaviour only. From local installation scripts will look for defined values in tra file. Based on the key values image will get built.

**Comment by rameshpolishetti** [comment]
@LakshmiMekala User can always update `tra` file to control what artefacts to be copied into the BE container image.

**Comment by LakshmiMekala** [comment]
Closing ticket as per comments
