### ISSUE TITLE
Provide compatibility for Legacy AS/ActiveSpaces/FTL versions with BE 6.2.0 while building docker images

### ISSUE THREAD

**Issue by AdittyThakare** [TIBCOSoftware/be-tools#234]
Currently while building docker image with AS 2.4.1 and BE 6.2.0 getting following error:

`C:\Users\athakare\Downloads\be-tools-master\cloud\docker>build_image.bat -i app -a C:\Docker\customerorder_target -s C:\Docker\Inst_6.2 -t test

Missing operand.
Missing operand.
ERROR: BE version: [6.2.0] not compatible with Activespaces version: [4.6.1].`

Kindly provide compatibility for applicable softwares with BE 6.2.0 like Legacy ActiveSpaces, ActiveSpaces, FTL etc.

**Comment by nareshkumarthota** [comment]
This will be addressed with PR #235
