### ISSUE TITLE
Add support for OpenTelemetry exporter charts

### ISSUE THREAD

**Issue by vpatil-tibco** [TIBCOSoftware/be-tools#236]
**Context**
BE 6.2 will support OpenTelemetry with options to export to a few exporters like otlp, zipkin and jaeger. The idea is to enhance our helm support to allow users to include these charts if their project uses open telemetry

**Alternatives**
Manually set these up and update BE configurations to to leverage these.

**Has the feature been requested before?**
Not yet.

**If the feature request is approved, would you be willing to submit a PR?**
Yes

**Comment by LakshmiMekala** [comment]
This is implemented and made available in the branch https://github.com/TIBCOSoftware/be-tools/tree/feature-be620

**Comment by tsaxena18** [comment]
Verified OpenTelemetry exporter charts with BE 6.2.0 using Jaeger, Zipkin & OTLP as exporter and found expected behavior. No issues. I could access the Jaeger/Zipkin UI dashboard and could see the traces for BE application.
