### ISSUE TITLE
Support for BE 6.2 items

### ISSUE THREAD

**Issue by vpatil-tibco** [TIBCOSoftware/be-tools#237]
**Context**
BE 6.2 will be supporting following features that need to be made available via helm,

1. Async API spec - /asyncapi
2. Ping/heartbeat - /ping

All are on the same port, which is configurable. Also a property to enable this server altogether. So we will need 2 inputs in values.yaml.
Enable - (Default value - false) - maps to BE property - be.engine.api.spec.enable 
Port - (Default value - 8180) - maps to BE property - be.engine.http.ping.port

**Alternatives**
No

**Has the feature been requested before?**
Yes, asked by PSG /customers.

**If the feature request is approved, would you be willing to submit a PR?**
Yes

**Comment by rameshpolishetti** [comment]
This is implemented and made available in the branch https://github.com/TIBCOSoftware/be-tools/tree/feature-be620

**Comment by jgirase** [comment]
Tested following scenarios for Open API/Async API spec on AWS EKS specifically for http channel,
1.Ping service
2.Access Async api json/yaml at runtime using LoadBalancer service type
3.Import Async api json/yaml  in studio using hosted url
4.Access Open api json/yaml/swagger at runtime using LoadBalancer service type
5.Import Open api json/yaml  in studio using hosted url
6.HTTP client/server communication using ClusterIP service type for open api spec
Find attached logs for reference.
[Open_Async_API_EKS_http.zip](https://github.com/TIBCOSoftware/be-tools/files/7446017/Open_Async_API_EKS_http.zip)

@tsaxena18 Please update status for Kafka/Jms channels

**Comment by rameshpolishetti** [comment]
> As per latest changes, openapi spec will be available on channel port which is defined in project http channel shared resource. Ping and async api will be accessible same as previously on ping port. Additionally swagger can be accessible for open api spec on /swagger/index.html.
> 
> Reference endpoints,
> 
> http://:8180/ping
> 
> http://:8180/asyncapi?chName=/Channels/HTTP
> 
> http://:7070/swagger/index.html
> 
> http://:7070/openapi.yaml
> 
> http://:7070/openapi.json
> 
> where 8180 is ping port and 7070 is http channel port.

@jgirase Updated Helm chart install notes accordingly.

**Comment by tsaxena18** [comment]
Validated following scenarios for Async API spec for Kafka & JMS channel,
1. Ping service
2. Access Async api json/yaml at runtime using LoadBalancer service type.
3. Import Async api json/yaml in studio using hosted url.
Attached logs for the reference. 
[AsyncAPI_JMS_Kafka.zip](https://github.com/TIBCOSoftware/be-tools/files/7447447/AsyncAPI_JMS_Kafka.zip)

**Comment by jgirase** [comment]
@rameshpolishetti I can see changes in notes related to async api spec. However I dont see any information related to openapi spec. Please confirm if its intentional

**Comment by rameshpolishetti** [comment]
> @rameshpolishetti I can see changes in notes related to async api spec. However I dont see any information related to openapi spec. Please confirm if its intentional

Yes @jgirase, notes are updated for async api spec because helm chart explicitly exposes dedicated xxx-apispec-service to serve async api spec. Same is not in case of openapi.

**Comment by tsaxena18** [comment]
@rameshpolishetti Can we update this below section in values.yaml for info on OpenAPI spec as well as we cannot find any. Also we are mentioning 3 end-points and listing only two. That also needs to be updated.
apispecservice:
  enabled: false      # Set to true - to enable API spec service which exposes 3 end-points (/ping & /asyncapi)
  port:               # Define to override the default port (8180)
  type: ClusterIP     # service type. Supported values: NodePort, LoadBalancer or ClusterIP

**Comment by rameshpolishetti** [comment]
Thank you @tsaxena18 for spotting out, I have updated values.yaml comments section.
Also note that Helm install notes would not mention about "/ping" as it is not meant for external consumption from outside the cluster, instead it is used for BE engine/pod health checks.
Regarding OpenAPI, there is no configuration made available through Helm chart hence no mention around this. OpenAPI spec is directly accessible through HTTP/Channel endpoint which BE documentation covers.

**Comment by rameshpolishetti** [comment]
Closing the issue as it is tested and merged to master.
