### ISSUE TITLE
Add provision to deploy BE app into user specified namespace using BE helm chart

### ISSUE THREAD

**Issue by rameshpolishetti** [TIBCOSoftware/be-tools#239]
**Context**
Currently, by using BE helm chart, user can deploy BE app into the `default` namespace only. There is no provision to specify desired namespace.

Add option to accept namespace through BE helm chart values.yaml

**Alternatives**
Need to update BE helm chart template files in several places.

**Has the feature been requested before?**
Yes, asked by PSG /customers

**If the feature request is approved, would you be willing to submit a PR?**
Yes

**Comment by LakshmiMekala** [comment]
Created PR #242 with required implementation

**Comment by rameshpolishetti** [comment]
This is feature is now available in master.

**Comment by tsaxena18** [comment]
Verified with BE 6.1.1 and with latest build of BE 6.2.0, it is working fine. I am able to deploy Helm with user defined namespace successfully.

**Comment by rameshpolishetti** [comment]
Closing the issue as the feature is verified successfully.
