### ISSUE TITLE
BE 6.2.1 - Build image fails

### ISSUE THREAD

**Issue by spantalo** [TIBCOSoftware/be-tools#254]
### Version Information
| Software       | Version(s)     |
| -------------- | -------------- |
| BusinessEvents |      6.2.1          |
| OS Type?       |      Ubuntu          |
| OS Version?    |      20.04          |
| Docker         |        20.10.7        |
| Kubernetes     |        NA        |
| Helm           |          NA      |

### What is the expected behavior?
Docker image is created

### What is the actual behavior?
Docker build fails with error: 
#14 125.2 Cannot open file /opt/tibco/be/6.2/bin/be-engine.tra for read at be_docker_install.pm line 590.

### Please provide a unit test that demonstrates the bug.
Just follow base image build instructions

### Other notes on how to reproduce the issue?
installers used during build: BE6.2.1, AS2.4.1 and AS2.4.1 HF-005

Please note: the same procedure works when using BE 6.2.0 installer (TIB_businessevents-enterprise_6.2.0_linux26gl25_x86_64.zip).

### Please provide log files.

`INFO: Building container image with the build tool[docker].
INFO: Supplied/Derived Data:
------------------------------------------------------------------------------
INFO: INSTALLER DIRECTORY          : [/mnt/hgfs/tmp/BE621/installers]
INFO: APPLICATION DATA DIRECTORY   : [/home/ubuntu/Desktop/Pirelli/deploy]
INFO: BE VERSION                   : [6.2.1]
INFO: AS LEGACY VERSION            : [2.4.1]
INFO: AS LEGACY HF                 : [006]
INFO: CDD FILE NAME                : [WhereIs.cdd]
INFO: EAR FILE NAME                : [WhereIs.ear]
INFO: DOCKERFILE                   : [./dockerfiles/Dockerfile]
INFO: IMAGE TAG                    : [whereis:1.0]
INFO: BUILD TOOL                   : [docker]
INFO: JRE VERSION                  : [11]
------------------------------------------------------------------------------
INFO: Copying package: [/mnt/hgfs/tmp/BE621/installers/TIB_businessevents-enterprise_6.2.1_linux26gl25_x86_64.zip]
INFO: Copying package: [/mnt/hgfs/tmp/BE621/installers/TIB_activespaces_2.4.1_linux_x86_64.zip]
INFO: Copying package: [/mnt/hgfs/tmp/BE621/installers/TIB_activespaces_2.4.1_HF-006_linux_x86_64.zip]

INFO: Building container image.

[+] Building 140.2s (14/22)                                                                                                                                           
 => [internal] load build definition from Dockerfile                                                                                                             0.0s
 => => transferring dockerfile: 3.88kB                                                                                                                           0.0s
 => [internal] load .dockerignore                                                                                                                                0.0s
 => => transferring context: 2B                                                                                                                                  0.0s
 => [internal] load metadata for docker.io/library/ubuntu:20.04                                                                                                  2.6s
 => [intermediate  1/13] FROM docker.io/library/ubuntu:20.04@sha256:626ffe58f6e7566e00254b638eb7e0f3b11d4da9675088f4781a50ae288f3322                             5.6s
 => => resolve docker.io/library/ubuntu:20.04@sha256:626ffe58f6e7566e00254b638eb7e0f3b11d4da9675088f4781a50ae288f3322                                            0.0s
 => => sha256:7b1a6ab2e44dbac178598dabe7cff59bd67233dba0b27e4fbd1f9d4b3c877a54 28.57MB / 28.57MB                                                                 3.9s
 => => sha256:626ffe58f6e7566e00254b638eb7e0f3b11d4da9675088f4781a50ae288f3322 1.42kB / 1.42kB                                                                   0.0s
 => => sha256:7cc0576c7c0ec2384de5cbf245f41567e922aab1b075f3e8ad565f508032df17 529B / 529B                                                                       0.0s
 => => sha256:ba6acccedd2923aee4c2acc6a23780b14ed4b8a5fa4e14e252a23b846df9b6c1 1.46kB / 1.46kB                                                                   0.0s
 => => extracting sha256:7b1a6ab2e44dbac178598dabe7cff59bd67233dba0b27e4fbd1f9d4b3c877a54                                                                        1.2s
 => [internal] load build context                                                                                                                               14.3s
 => => transferring context: 1.29GB                                                                                                                             14.3s
 => [intermediate  2/13] RUN apt-get update  && apt-get install -y unzip procps findutils tar                                                                   10.4s
 => [intermediate  3/13] COPY lib/*.pm lib/*.py lib/*.sh installers/* lib/run lib/deletelist.txt /home/tibco/be/                                                 9.9s 
 => [intermediate  4/13] COPY gvproviders /home/tibco/be/gvproviders                                                                                             0.0s 
 => [intermediate  5/13] COPY app/* /opt/tibco/be/ext/                                                                                                           0.0s 
 => [intermediate  6/13] WORKDIR /home/tibco/be                                                                                                                  0.0s 
 => [intermediate  7/13] RUN chmod +x *.sh *.pm                                                                                                                  0.4s 
 => [intermediate  8/13] RUN perl -I. -Mbe_docker_install -e "be_docker_install::install_ftl('na','na')"                                                         0.3s 
 => [intermediate  9/13] RUN perl -I. -Mbe_docker_install -e "be_docker_install::install_activespaces('na','na')"                                                0.5s
 => ERROR [intermediate 10/13] RUN perl -I. -Mbe_docker_install -e "be_docker_install::install_be('6.2.1','enterprise','na','na','006','2.4.1')"               110.2s
------                                                                                                                                                                
 > [intermediate 10/13] RUN perl -I. -Mbe_docker_install -e "be_docker_install::install_be('6.2.1','enterprise','na','na','006','2.4.1')":                            
#14 0.365                                                                                                                                                             
#14 0.365 INFO:Installing ActiveSpaces Legacy 2.4.1...
#14 29.47 
#14 29.47 INFO:Installing ActiveSpaces Legacy 2.4.1...DONE
#14 29.47 
#14 29.47 
#14 29.47 INFO:Installing BusinessEvents 6.2.1...
#14 110.1 Cannot open file /opt/tibco/be/6.2.1/bin/be-engine.tra for read at be_docker_install.pm line 592.
------
executor failed running [/bin/sh -c perl -I. -Mbe_docker_install -e "be_docker_install::install_be('$BE_PRODUCT_VERSION','enterprise','$BE_PRODUCT_ADDONS','$BE_PRODUCT_HOTFIX','$AS_PRODUCT_HOTFIX','$AS_VERSION')"]: exit code: 2
ERROR: Container build failed.
Deleted build cache objects:
`

### Any possible solutions?
None at the moment, still working on it. 

### Can you identify the location in the source code where the problem exists?
be_docker_install.pm:590
  open (IN, $fileName) || die "Cannot open file ".$fileName." for read";     

### If the bug is confirmed, would you be willing to submit a PR?
Yes

**Comment by nareshkumarthota** [comment]
Just now downloaded be 6.2.1(V11.1-GA) -- TIB_businessevents-enterprise_6.2.1_linux26gl25_x86_64.zip. Tried building image in my machine. Build is success. Can you try clearing your docker cache and rebuild.

Below are logs from my build:

naresh@naresh-ThinkPad-P50:~/go/src/github.com/TIBCOSoftware/be-tools/cloud/docker$ ./build_image.sh -i app -a /home/naresh/Downloads/tibproducts/app/be620/inmem -s /home/naresh/Downloads/tibproducts/be621 -t testbe621:v1
INFO: Building container image with the build tool[docker].
INFO: Supplied/Derived Data:
------------------------------------------------------------------------------
INFO: INSTALLER DIRECTORY          : [/home/naresh/Downloads/tibproducts/be621]
INFO: APPLICATION DATA DIRECTORY   : [/home/naresh/Downloads/tibproducts/app/be620/inmem]
INFO: BE VERSION                   : [6.2.1]
INFO: AS LEGACY VERSION            : [2.4.1]
INFO: AS LEGACY HF                 : [006]
INFO: CDD FILE NAME                : [fd.cdd]
INFO: EAR FILE NAME                : [fd.ear]
INFO: DOCKERFILE                   : [./dockerfiles/Dockerfile]
INFO: IMAGE TAG                    : [testbe621:v1]
INFO: BUILD TOOL                   : [docker]
INFO: JRE VERSION                  : [11]
------------------------------------------------------------------------------
INFO: Copying package: [/home/naresh/Downloads/tibproducts/be621/TIB_businessevents-enterprise_6.2.1_linux26gl25_x86_64.zip]
INFO: Copying package: [/home/naresh/Downloads/tibproducts/be621/TIB_activespaces_2.4.1_linux_x86_64.zip]
INFO: Copying package: [/home/naresh/Downloads/tibproducts/be621/TIB_activespaces_2.4.1_HF-006_linux_x86_64.zip]

INFO: Building container image.


[+] Building 203.4s (23/23) FINISHED                                                                                                                                                                          
 => [internal] load build definition from Dockerfile                                                                                                                                                     0.2s
 => => transferring dockerfile: 3.88kB                                                                                                                                                                   0.0s
 => [internal] load .dockerignore                                                                                                                                                                        0.3s
 => => transferring context: 2B                                                                                                                                                                          0.0s
 => [internal] load metadata for docker.io/library/ubuntu:20.04                                                                                                                                          0.0s
 => [intermediate  1/13] FROM docker.io/library/ubuntu:20.04                                                                                                                                             0.3s
 => => resolve docker.io/library/ubuntu:20.04                                                                                                                                                            0.0s
 => [internal] load build context                                                                                                                                                                       11.4s
 => => transferring context: 1.29GB                                                                                                                                                                     10.0s
 => [intermediate  2/13] RUN apt-get update  && apt-get install -y unzip procps findutils tar                                                                                                           15.6s
 => [intermediate  3/13] COPY lib/*.pm lib/*.py lib/*.sh installers/* lib/run lib/deletelist.txt /home/tibco/be/                                                                                         1.0s 
 => [intermediate  4/13] COPY gvproviders /home/tibco/be/gvproviders                                                                                                                                     0.3s 
 => [intermediate  5/13] COPY app/* /opt/tibco/be/ext/                                                                                                                                                   0.2s 
 => [intermediate  6/13] WORKDIR /home/tibco/be                                                                                                                                                          4.6s 
 => [intermediate  7/13] RUN chmod +x *.sh *.pm                                                                                                                                                          0.5s 
 => [intermediate  8/13] RUN perl -I. -Mbe_docker_install -e "be_docker_install::install_ftl('na','na')"                                                                                                 0.5s 
 => [intermediate  9/13] RUN perl -I. -Mbe_docker_install -e "be_docker_install::install_activespaces('na','na')"                                                                                        0.4s
 => [intermediate 10/13] RUN perl -I. -Mbe_docker_install -e "be_docker_install::install_be('6.2.1','enterprise','na','na','006','2.4.1')"                                                             120.7s
 => [intermediate 11/13] RUN perl -I. -Mbe_docker_install -e "be_docker_install::replaceRunbeVersionToken('6.2.1','./run')"                                                                              0.7s
 => [intermediate 12/13] RUN perl -I. -Mbe_docker_install -e "be_docker_install::generateAnnotationIndexes('/opt/tibco/be/6.2', '/opt/tibco/tibcojre64/11')"  && rm -rf as_installers as_installers-hf   9.8s 
 => [intermediate 13/13] RUN ./prepare_finalimage.sh                                                                                                                                                     2.2s 
 => [stage-1 2/6] COPY --from=intermediate /home/tibco/be /home/tibco/be                                                                                                                                 0.1s 
 => [stage-1 3/6] COPY --from=intermediate /tibco_home /opt/tibco                                                                                                                                       15.1s 
 => [stage-1 4/6] RUN chmod +x /home/tibco/be/gvproviders/*.sh && /home/tibco/be/gvproviders/setup.sh na                                                                                                 0.5s 
 => [stage-1 5/6] RUN mkdir -p /mnt/tibco/be/logs  && mkdir -p /mnt/tibco/be/data-store  && ln -s /opt/tibco/be/6.2 /opt/tibco/be/latest                                                                 0.6s 
 => [stage-1 6/6] WORKDIR /home/tibco/be                                                                                                                                                                 0.0s 
 => exporting to image                                                                                                                                                                                  14.6s
 => => exporting layers                                                                                                                                                                                 14.6s
 => => writing image sha256:69502465767d0b5f9fa725148b93965746e2d937d7ac811c1d3da1fe5db357fe                                                                                                             0.0s
 => => naming to docker.io/library/testbe621:v1                                                                                                                                                          0.0s
Deleted build cache objects:
y0rr3rhhac62vcrxe5i6c9i3i
azlmunfaeiw6crc4njbfvj7r5
fjb6t43ilq1uv1s5bp7ohs38o
nairemxqmug9ylqre6vycq3ds
0o5zwou987ws9eogz73j7k7p6
7ihtk1t3vtd9num4e0xgz1h8x
zf1bvfz5p2n41hed1oq9fe2n1
p86ce755nl35c50lhvwz78wz5
8ndfmyqsk89isi281uu72dtfe
cy8pnwn2npeofwrgfvidh944e
bicjnc0m2mvvqpqero3zumflc
wfkiedevcxci5r9ydmvxmadzp
hht3kbqwzqa9gtkmk4vgxhlca
l3pt5ntnsn8p4bygfnidqla60
mr23vht1dfkrssekpixylm2bp

Total reclaimed space: 4.678GB
INFO: Deleting folder: [tmp_6956].
INFO: Container build successfull using the build tool[docker]. Image Name: [testbe621:v1]

=================RUNNING CONTAINER STRUCTURE TESTS=================

-----------------------------------------------
INFO: image name:          [testbe621:v1]
INFO: be version:          [6.2]
INFO: as legacy version:   [2.4]
-----------------------------------------------


================================
====== Test file: be.yaml ======
================================

======================================
====== Test file: aslegacy.yaml ======
======================================
=== RUN: Command Test: beengine without cdd
--- PASS
duration: 2.452540632s
=== RUN: File Content Test: BE TRA Updated with AS home
--- PASS
duration: 0s
=== RUN: File Existence Test: BE Path
--- PASS
duration: 0s
=== RUN: File Existence Test: BE Engine Binary
--- PASS
duration: 0s
=== RUN: File Existence Test: BE Engine TRA File
--- PASS
duration: 0s
=== RUN: File Existence Test: BE Path Lib
--- PASS
duration: 0s
=== RUN: File Existence Test: BE Lib File
--- PASS
duration: 0s
=== RUN: File Existence Test: Gvproviders Path
--- PASS
duration: 0s
=== RUN: File Existence Test: Gvproviders File
--- PASS
duration: 0s
=== RUN: File Existence Test: Docker Run File
--- PASS
duration: 0s
=== RUN: File Existence Test: Cdd file
--- PASS
duration: 0s
=== RUN: File Existence Test: Ear file
--- PASS
duration: 0s
=== RUN: File Existence Test: JAVA Home
--- PASS
duration: 0s
=== RUN: Metadata Test
--- PASS
duration: 0s
=== RUN: File Content Test: BE TRA Updated with AS home
--- PASS
duration: 0s
=== RUN: File Existence Test: AS Lib Path
--- PASS
duration: 0s
=== RUN: File Existence Test: AS Lib Jar File
--- PASS
duration: 0s

=======================================
=============== RESULTS ===============
=======================================
Passes:      17
Failures:    0
Duration:    2.452540632s
Total tests: 17

PASS

=================END OF CONTAINER STRUCTURE TESTS==================

naresh@naresh-ThinkPad-P50:~/go/src/github.com/TIBCOSoftware/be-tools/cloud/docker$ docker images
REPOSITORY                                     TAG                 IMAGE ID       CREATED              SIZE
testbe621                                      v1                  69502465767d   About a minute ago   575MB

**Comment by nareshkumarthota** [comment]
If you are still facing the issue, Kindly share debug logs.
Steps to enable debug mode installation:
Go to file `<BE_TOOLS_HOME>/cloud/docker/lib/be_docker_install.pm` In line no 16 edit variable `DEBUG_ENABLE` value to 1.

**Comment by spantalo** [comment]
Hi Naresh, it worked after purging docker cache as you suggested: docker builder prune
Thanks for the hint!
