### ISSUE TITLE
externalizing CDD settings in a configmap

### ISSUE THREAD

**Issue by mulcahey** [TIBCOSoftware/be-tools#259]
Hi - In the old world, we could build an EAR file in Studio and this did not depend on the CDD. So changes to the CDD could be made without having to rebuild the EAR. In the new world of container images, we now ask that the EAR and CDD be placed in an artifacts directory (which our build_image script looks to). So the CDD is no longer separated from the build process.

Is it recommended/supported to handle the entire CDD file as an external configmap for running on K8S? Or may we only externalize settings through global variables?

Thanks.

**Comment by vpatil-tibco** [comment]
We already have an option to do that using s2i (https://github.com/TIBCOSoftware/be-tools/wiki/Building-TIBCO-BusinessEvents-Application). It for a more dev centric case, when the ear and cdd are more prone to changes.

So it works off a 2 image system, where there is a base image with core BE and then an quick small app based BE which takes simply the ear and cdd.

Recently we added a critical performance feature which needs cdd during the image construction time. Technically we can figure a way to externalize it in general but then that performance feature will be lost. We will have to validate how relevant of an ROI would that provide.

For now s2i is the standard way for frequently changing application ear/cdd.
