### ISSUE TITLE
Permission issue on startup of the BE container when docker image created on Linux

### ISSUE THREAD

**Issue by umueller-de** [TIBCOSoftware/be-tools#262]
### Version Information
| Software       | Version(s)     |
| -------------- | -------------- |
| BusinessEvents |   6.2.1             |
| OS Type?       |      Ubuntu          |
| OS Version?    |     22.04           |
| Docker         |      20.10.12          |
| Kubernetes     |                |
| Helm           |                |

The docker image created on a Linux system with the docker scripts in zip file.

Startup failed with below error:
"docker: Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "./run": permission denied: unknown."

Workaround for now:
Before build the container set correct permissions to the startup scripts.
chmod -R +x *

Note:
The zip file should be created on a Unix machine with correct permissions of the Unix scripts or the installer script sets the correct permissions correctly for the BE startup script (/home/tibco/be/run).

**Comment by nareshkumarthota** [comment]
I tried on my machine. I am able to run the image successfully. Attached logs.

[be-tools-master-logs.log](https://github.com/TIBCOSoftware/be-tools/files/8126271/be-tools-master-logs.log)

**Comment by nareshkumarthota** [comment]
@umueller-de  Changes pushed to branch `fix-issue-262` . Please validate and confirm.

**Comment by rameshpolishetti** [comment]
This fix is available in the master, as the respective PR #263 validated and accepted into the master.

**Comment by umueller-de** [comment]
Tested and confirm its fixed.
Thanks
