### ISSUE TITLE
Not able to create BE 6.2.2 docker image with AS 2.4.2.

### ISSUE THREAD

**Issue by tsaxena18** [TIBCOSoftware/be-tools#271]
### Version Information
| Software       | Version(s)     |
| -------------- | -------------- |
| BusinessEvents |        6.2.2        |
| OS Type?       |    Linux          |
| OS Version?    |    CentOS 7.9            |
| Docker         |    20.10.14            |
| Kubernetes     |   NA             |
| Helm           |      NA          |

### What is the expected behavior?
The docker image should be build successfully with BE 6.2.2 + AS 2.4.2.

### What is the actual behavior?
Not able to create BE 6.2.2 image with AS 2.4.2.  The command exits with error as,
ERROR: BE version: [6.2.2] not compatible with Activespaces(legacy) version: [2.4.2].

### Please provide a unit test that demonstrates the bug.
[apps@tsaxena-z820 docker]$ ./build_image.sh -i app -a /home/apps/Testing/temp/fdc-v3 -s /home/apps/Installers/BE/622/v3 -t fdcas242:622
ERROR: BE version: [6.2.2] not compatible with Activespaces(legacy) version: [2.4.2].

**Comment by nareshkumarthota** [comment]
As per communication from team. be 6.2.2 should support only as 2.4.1
