### ISSUE TITLE
JMX Connection to BE container failed when docker container started in a bridged network 

### ISSUE THREAD

**Issue by umueller-de** [TIBCOSoftware/be-tools#279]
**Environment**:
Docker (tested on Windows)
BE 6.2.1

**Issue**:
A JMX console connection from external system to the BE application not work when BE docker container started in a bridged network (docker desktop). The JMX port exposed correctly (telnet connection work).
This is caused by the be-engine.tra  property "java.property.java.rmi.server.hostname" added by the startup script "run" (points to the assigned ip/hostname instead of localhost/0.0.0.0).
I recommend to set the property to 0.0.0.0 instead of the IP of the container. 

**Workaround for now:**
As a workaround for now modify lib/run script and add below line at the end of the script before BE-Agent starts and set hostname to "localhost" or "0.0.0.0"

...
# added line below to be able to connect to JMX console from docker host
echo java.property.java.rmi.server.hostname localhost >>
/opt/tibco/be/6.2/bin/be-engine.tra

echo "$RUNCMD"
exec $RUNCMD

**Comment by LakshmiMekala** [comment]
Hi @umueller-de 

At the container run time, user can add env `tra.java.property.java.rmi.server.hostname="systemip or system hostname"` and connect to jconsole with localhost:5555, connection would be successful.
