### ISSUE TITLE
BE container application runtime configurations and its order of precedence

### ISSUE THREAD

**Issue by rameshpolishetti** [TIBCOSoftware/be-tools#289]
**Context**
TIBCO BE application deployed on a cloud platform pulls its runtime configurations before container startup from various sources including Pod environment, ConfigMaps, Secrets and GV providers. However, related documentation is vague.

Add a section in the `wiki` describing all possible ways to inject runtime configurations into the BE container application and its order of precedence.

**Alternatives**
NA

**Has the feature been requested before?**
NA

**If the feature request is approved, would you be willing to submit a PR?**
Yes

**Comment by LakshmiMekala** [comment]
Included new wiki [page](https://github.com/TIBCOSoftware/be-tools/wiki/GlobalVariables) which details about order of precedence of global variables at container runtime.

**Comment by LakshmiMekala** [comment]
Here is the order of precedence of global variables at container runtime:

- GV framework order -> HTTP,CONSUL,AWS -

    p1- AWS
    p2- CONSUL
    p3- HTTP

- Environment variables from envVars section of helm chart
- Secret(if morethan one secret, then last mentioned in the list considers as final env's- envVarsFromSecrets-helm chart)
- Configmap already exists(envVarsFromConfigMaps- helm chart)
- Configmap - newly created at helm release time(configs)

**Comment by rameshpolishetti** [comment]
closing the issue as it is fixed.
