### ISSUE TITLE
Evaluate CyberArk for Secret Manager

### ISSUE THREAD

**Issue by vpatil-tibco** [TIBCOSoftware/be-tools#292]
**Context**
There has been an ask by customers around using CyberArk as a secrets manager. We need to evaluate if our existing framework for GV's, especially simple http end point based option is sufficient.

**Alternatives**
Use the http based GV option or build additional option as needed.

**Has the feature been requested before?**
Yes by Entergy, Citi

**If the feature request is approved, would you be willing to submit a PR?**
Yes

**Comment by rameshpolishetti** [comment]
This has been implemented through the PR #301

**Comment by rameshpolishetti** [comment]
Closing the issue as it is implemented.
