### ISSUE TITLE
RHEL 9 : Docker image build script fails when Installers are provided as source.

### ISSUE THREAD

**Issue by tsaxena18** [TIBCOSoftware/be-tools#296]
### Version Information
| Software       | Version(s)     |
| -------------- | -------------- |
| BusinessEvents |      6.2.2          |
| OS Type?       |   RHEL             |
| OS Version?    |   9.0             |
| Docker         |         20.10.18       |
| Kubernetes     |       NA         |
| Helm           |     NA           |

### What is the expected behavior?
The docker image should be built successfully on RHEL 9 using installers as source with default dockerfile.

### What is the actual behavior?
The image build script ran fine when BE_HOME is passed as source but fails when installers are provided as source in command as given below : 
 ./build_image.sh -i app -a /home/svcmasrel2qa/tanmay/temp -s /home/svcmasrel2qa/Installers/622/44 -t fd2:622

There is no issue with the same use case when tried on RHEL 8.

### Please provide a unit test that demonstrates the bug.
[svcmasrel2qa@na2devbeqa06 docker]$ ./build_image.sh -i app -a /home/svcmasrel2qa/tanmay/temp -s /home/svcmasrel2qa/Installers/622/44 -t fd2:622
INFO: Supplied/Derived Data:
INFO: Building container image with the build tool[docker].
INFO: INSTALLER DIRECTORY          : [/home/svcmasrel2qa/Installers/622/44]
INFO: APPLICATION DATA DIRECTORY   : [/home/svcmasrel2qa/tanmay/temp]
INFO: BE VERSION                   : [6.2.2]
INFO: BE ADDONS                    : [process]
INFO: AS LEGACY VERSION            : [2.4.1]
INFO: CDD FILE NAME                : [fd.cdd]
INFO: EAR FILE NAME                : [fd.ear]
INFO: DOCKERFILE                   : [./dockerfiles/Dockerfile]
INFO: IMAGE TAG                    : [fd2:622]
INFO: BUILD TOOL                   : [docker]
INFO: JRE VERSION                  : [11]
INFO: Copying package: [/home/svcmasrel2qa/Installers/622/44/TIB_businessevents-enterprise_6.2.2_linux26gl25_x86_64.zip]
INFO: Copying package: [/home/svcmasrel2qa/Installers/622/44/TIB_activespaces_2.4.1_linux_x86_64.zip]
INFO: Copying package: [/home/svcmasrel2qa/Installers/622/44/TIB_businessevents-process_6.2.2_linux26gl25_x86_64.zip]

INFO: Building container image.

[+] Building 45.4s (15/26)
 => [internal] load build definition from Dockerfile                                                                                                                                    0.0s
 => => transferring dockerfile: 4.39kB                                                                                                                                                  0.0s
 => [internal] load .dockerignore                                                                                                                                                       0.0s
 => => transferring context: 2B                                                                                                                                                         0.0s
 => [internal] load metadata for docker.io/library/ubuntu:20.04                                                                                                                         0.4s
 => CACHED [intermediate  1/16] FROM docker.io/library/ubuntu:20.04@sha256:9c2004872a3a9fcec8cc757ad65c042de1dad4da27de4c70739a6e36402213e3                                             0.0s
 => [internal] load build context                                                                                                                                                      13.2s
 => => transferring context: 1.37GB                                                                                                                                                    13.2s
 => [intermediate  2/16] RUN apt-get update  && apt-get install -y unzip procps findutils tar                                                                                          11.7s
 => [intermediate  3/16] COPY lib/*.pm lib/*.py lib/*.sh installers/* lib/run lib/deletelist.txt /home/tibco/be/                                                                        3.3s
 => [intermediate  4/16] COPY gvproviders /home/tibco/be/gvproviders                                                                                                                    0.0s
 => [intermediate  5/16] COPY app/* /opt/tibco/be/ext/                                                                                                                                  0.0s
 => [intermediate  6/16] WORKDIR /home/tibco/be                                                                                                                                         0.0s
 => [intermediate  7/16] RUN chmod +x *.sh *.pm run                                                                                                                                     0.5s
 => [intermediate  8/16] RUN perl -I. -Mbe_docker_install -e "be_docker_install::install_hawk('na','na')"                                                                               0.5s
 => [intermediate  9/16] RUN perl -I. -Mbe_docker_install -e "be_docker_install::install_ftl('na','na')"                                                                                0.5s
 => [intermediate 10/16] RUN perl -I. -Mbe_docker_install -e "be_docker_install::install_activespaces('na','na')"                                                                       0.4s
 => ERROR [intermediate 11/16] RUN perl -I. -Mbe_docker_install -e "be_docker_install::install_be('6.2.2','enterprise','process','na','na','2.4.1')"                                   26.1s

 > [intermediate 11/16] RUN perl -I. -Mbe_docker_install -e "be_docker_install::install_be('6.2.2','enterprise','process','na','na','2.4.1')":
#15 0.483
#15 0.483 INFO:Installing ActiveSpaces Legacy 2.4.1...
#15 6.640
#15 6.640 INFO:Installing ActiveSpaces Legacy 2.4.1...DONE
#15 6.640
#15 6.640
#15 6.640 INFO:Installing BusinessEvents 6.2.2...
#15 26.01 Cannot open file /opt/tibco/be/6.2/bin/be-engine.tra for read at be_docker_install.pm line 620.

executor failed running [/bin/sh -c perl -I. -Mbe_docker_install -e "be_docker_install::install_be('$BE_PRODUCT_VERSION','enterprise','$BE_PRODUCT_ADDONS','$BE_PRODUCT_HOTFIX','$AS_PRODUCT_HOTFIX','$AS_VERSION')"]: exit code: 2
ERROR: Container build failed.

### Please provide log files.
[RHEL9-BE622.txt](https://github.com/TIBCOSoftware/be-tools/files/9776168/RHEL9-BE622.txt)

**Comment by nareshkumarthota** [comment]
Issue is with default ulimit value in container is very high. BE installer exiting abruptly because of high ulimit value. Workaround can be modify your dockerfile to limit the ulimit value for be installation instruction.

`
RUN  ulimit -n 1048576 && perl -I. -Mbe_docker_install -e "be_docker_install::install_be('$BE_PRODUCT_VERSION','enterprise','$BE_PRODUCT_ADDONS','$BE_PRODUCT_HOTFIX','$AS_PRODUCT_HOTFIX','$AS_VERSION')"
`

Will try to update permanent solution soon.
