### ISSUE TITLE
A Windows Image created from an existing BE installation not work - startup error "Failed to open Registry key for JRE, "SOFTWARE\JavaSoft\Java Runtime Environment"

### ISSUE THREAD

**Issue by umueller-de** [TIBCOSoftware/be-tools#297]
### Version Information
| Software       | Version(s)     |
| -------------- | -------------- |
| BusinessEvents |     6.2.2           |
| OS Type?       |   Windows (mcr.microsoft.com/windows/servercore:ltsc2019)      |
| Docker         |  Windows Docker Desktop              |

A Windows Image created from an existing BE installation not work - startup error "Failed to open Registry key for JRE, "SOFTWARE\JavaSoft\Java Runtime Environment"

Please confirm that's a script issue or additional installation steps required to get it working (not documented yet)

Image created with:
`build_image.bat -i app -a "c:\temp\FDAppFiles" -s "D:\tibco_be622base\be\6.2" -t fdwin:be621
`
**Erorr reported when try to start the container:**
```
docker run -it --rm -p 8108:8108 -p 5555:5555 -e PU=default -e ENGINE_NAME=IA1_FDSample  fdwin:be621

JMX_PORT: 5556
BE_HOME: c:/tibco/be/6.2
TRA FILE: c:/tibco/be/6.2\bin\be-engine.tra
ENGINE NAME: IA1_FDSample
CDD FILE: c:/tibco/be/application/fd.cdd
PROCESSING UNIT: default
EAR FILE: c:/tibco/be/application/ear/fd.ear
AS DISCOVER URL: tcp://EF2C1231BD3D:50000
AS LISTEN URL: tcp://EF2C1231BD3D:50000
#BE props file
Starting Application..
Failed to open Registry key for JRE, "SOFTWARE\JavaSoft\Java Runtime Environment"
Failed to open Registry key for JRE's current version, ""
```

**Comment by nareshkumarthota** [comment]
@umueller-de  can you build again and check. Its working at my end.

[wind-beapp-frominstall.txt](https://github.com/TIBCOSoftware/be-tools/files/9786820/wind-beapp-frominstall.txt)

**Comment by umueller-de** [comment]
I did another test.
The image can be started correctly if you create the image on a machine where BE is installed in the default location "**c:\tibco\be\<version>**"
e.g.,
build_image.bat -i app -a "c:\temp\FDAppFiles" -s "c:\tibco\be\6.2" -t fdwin:be621

The start fail when build the image from a different location.
e.g.,
build_image.bat -i app -a "c:\temp\FDAppFiles" -s "**D:\tibco_be622base\be\6.2**" -t fdwin:be621

In that case the location of the java installation is incorrect in the "c:\tibco\be\bin\be-engine.tra"

The java version copied to: 
"**c:/tibco/java/11**" but  BE expects java based on the be-engine.tra file:
"**c:/tibco/tibcojre64/11**"

be-engine.tra
```
tibco.env.TIB_JAVA_HOME=c:/tibco/tibcojre64/11
...
tibco.env.JVM_LIB_PATH=c:/tibco/tibcojre64/11/bin/server/jvm.dll
tibco.env.JVM_LIB_DIR=c:/tibco/tibcojre64/11/bin/server
```

**Comment by nareshkumarthota** [comment]
@umueller-de  please validate once.

**Comment by umueller-de** [comment]
Tested new master scripts and confirm, container starts correctly.
