### ISSUE TITLE
CyberArk Conjur GV provider not able to fetch when it contains single GV value

### ISSUE THREAD

**Issue by rameshpolishetti** [TIBCOSoftware/be-tools#303]
### Version Information
| Software       | Version(s)     |
| -------------- | -------------- |
| BusinessEvents |       6.2         |
| OS Type?       |       Ubuntu         |
| OS Version?    |       22.04         |
| Docker         |        20.10        |

### What is the expected behavior?
GV value should be pulled from CyberArk Conjur server and added to the property file.

### What is the actual behavior?
CyberArk Conjur GV provider not able to fetch GV values when Conjur server contains single (ONE) GV.

### Please provide a unit test that demonstrates the bug.
Follow be-tools/wiki document and create only one GV in the Conjur server.

### Other notes on how to reproduce the issue?
NA

### Please provide log files.
NA

### If the bug is confirmed, would you be willing to submit a PR?
Yes

**Comment by ykalidin** [comment]
As confirmed by conjur, we dont have a way to get json output when single secret is used.
As of now we are manually formatting the output to json. Changes are in fix-issue-303 branch.Please verify.

**Comment by rameshpolishetti** [comment]
closing the issue as it is fixed through the PR #318
