### ISSUE TITLE
Add AWS Session Token based authentication support for BE container image

### ISSUE THREAD

**Issue by rameshpolishetti** [TIBCOSoftware/be-tools#317]
**Context**
Add support to connect and pull GVs from AWS using new portal (i.e. TAO / Tibco AWS Organization) authentication mechanism which is based on "AWS Session Token".

**Alternatives**
NO

**Has the feature been requested before?**
NA

**If the feature request is approved, would you be willing to submit a PR?**
Yes

**Comment by ykalidin** [comment]
Changed to work with AWS session token in branch `feature-aws-st-auth`.
