### ISSUE TITLE
BE6.2 - Node Affinity in Bitnami Helm chart Azure

### ISSUE THREAD

**Issue by msantibatibco** [TIBCOSoftware/be-tools#322]
### Version Information
| Software       | Version(s)     |
| -------------- | -------------- |
| BusinessEvents |      6.2.2          |
| OS Type?       |        Linux :Ubuntu      |
| OS Version?    |       |
| Docker         |                |
| Kubernetes     |                |
| Helm           |        v2        |

### What is the expected behavior?
Set up Node Affinity/AntiAffinity like in: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#affinity-and-anti-affinity

### What is the actual behavior?
There's no documentation on how to set Node Affinity/AntiAffinity using Helm chart with values.yaml, also there's no confirmation of support for Node Affinity/Antiaffinity.

### Can you identify the location in the source code where the problem exists?
Yes, in attachment see values.yaml file

### If the bug is confirmed, would you be willing to submit a PR?
Yes / No _(Help can be provided if you need assistance submitting a PR)_
[helmwork_BE.zip](https://github.com/TIBCOSoftware/be-tools/files/11288289/helmwork_BE.zip)

**Comment by vpatil-tibco** [comment]
@msantibatibco  Pod affinity and antiaffinity are simply rules to achieve a particular deployment configuration. Can you outline what exactly does the customer want to achieve wrt to BE deployment configuration?

**Comment by msantibatibco** [comment]
@vpatil-tibco customer needs the following:

Client has the AKS cluster shared by multiple projects. But each project has dedicated set of nodes identified nodePool tag. It’s mainly to distinguish computing resources used by each project and hence identify costing.

In the past we’ve used nodeSelector – so project specific pods are deployed in respective nodes. The same approach is used by other project to avoid mix-up.

Below is the snippet from deployment yaml/json file.

"spec": {
                "affinity": {
                    "nodeAffinity": {
                        "requiredDuringSchedulingIgnoredDuringExecution": {
                            "nodeSelectorTerms": [
                                {
                                    "matchExpressions": [
                                        {
                                            "key": "hardware",
                                            "operator": "In",
                                            "values": [
                                                "oslcns"
                                            ]
                                        }
                                    ]
                                }
                            ]
                        }
                    }
                },

Thanks!

**Comment by vpatil-tibco** [comment]
Thanks @msantibatibco for the details. We will add node affinity support.

**Comment by msantibatibco** [comment]
Thanks! @vpatil-tibco.

**Comment by LakshmiMekala** [comment]
@msantibatibco @vpatil-tibco Node affinity related helm chart changes are available in [feature-node-affinity](https://github.com/TIBCOSoftware/be-tools/tree/feature-node-affinity) branch
