### ISSUE TITLE
Security vulnerabilities of BE-Tools

### ISSUE THREAD

**Issue by mmussett** [TIBCOSoftware/be-tools#323]
### Version Information
| Software       | Version(s)     |
| -------------- | -------------- |
| BusinessEvents |  6.2.2              |
| OS Type?       |    Linux            |
| OS Version?    |                |
| Docker         |      N          |
| Kubernetes     |    Y            |
| Helm           |     Y           |

### What is the expected behavior?
A number of critical security defects have been identified by customer during Prisma scan of container image built for BE-Tools

### What is the actual behavior?
Need review of Prisma report and critical defects addressing.

### If the bug is confirmed, would you be willing to submit a PR?
Yes / No _(Help can be provided if you need assistance submitting a PR)_

**Comment by mmussett** [comment]
Closing as duplicated issues.

**Comment by rameshpolishetti** [comment]
closing the issue.
