### ISSUE TITLE
Ignite inbuild cache - InferenceAgent not able to join the Ignite cluster with non-default discovery ports

### ISSUE THREAD

**Issue by umueller-de** [TIBCOSoftware/be-tools#324]
### Version Information
| Software       | Version(s)     |
| -------------- | -------------- |
| BusinessEvents |  6.2.2HF1              |
| OS Type?       |   Linux (K8s helm deployment)             |

### Issue:
The InferenceAgent(s) not able to join the Ignite cluster in a K8s deployment when modify the default Ignite listen port range "47500..47510"  in CDD and update the ports of the discovery service in helm chart.

e.g.,
CDD:
`<property name="listen-port" value="47600..47610"/>`

**Values.yaml:**
...
`# ignitePort: Specify ignite listen ports. Update if you have configured different values in the CDD (ignite configuration -> Listen Port)
ignitePort:
`
  dis0: 47600
  dis1: 47601
  dis2: 47602
  dis3: 47603
  dis4: 47604
  dis5: 47605
  dis6: 47606
  dis7: 47607
  dis8: 47608
  dis9: 47609
  dis10: 47610
...

Note:
The InferenceAgent joins the cluster correctly when you enable Flag "Act as CacheServer" (ProcessUnit).

### Any possible solutions?
In current version it is required to deploy each BE application in a separate namespace with default Ignite discovery ports

**Comment by rameshpolishetti** [comment]
@umueller-de looks you might be working on bit older helm chart. with the latest helm chart you should be able to deploy multiple applications in the same namespace.

**Comment by rameshpolishetti** [comment]
NOTE: As discussed, Take the latest helm chart, deploy multiple applications into the same namespace and inspect cache agents headless services and make sure that its endpoints are resolving to respective cache-pods only.

**Comment by umueller-de** [comment]
Issue fixed with latest deployment scripts.
