### ISSUE TITLE
Update the docker build image script for BE 6.3.0.

### ISSUE THREAD

**Issue by tsaxena18** [TIBCOSoftware/be-tools#326]
### Version Information
| Software       | Version(s)     |
| -------------- | -------------- |
| BusinessEvents |    6.3.0            |
| OS Type?       |    RHEL            |
| OS Version?    |   9.1             |
| Docker         |    23.0.4            |
| Kubernetes     |    NA            |
| Helm           |       NA         |

### What is the expected behavior?
Image should build successfully for BE 6.3.0.

### What is the actual behavior?
The script fails to run with below error :
[svcmasrel2qa@na2devbeqa06 docker]$ ./build_image.sh -i app -a /home/svcmasrel2qa/tanmay/fdcign -s /home/svcmasrel2qa/Installers/630/127 -t fdcign:v127
**ERROR: Unsupported be version[6.3.0]**

**Comment by rameshpolishetti** [comment]
Closing the issue as BE 6.3.0 version dependencies are updated.
