### ISSUE TITLE
BE 630 : Windows based docker image build process failed.

### ISSUE THREAD

**Issue by tsaxena18** [TIBCOSoftware/be-tools#329]
### Version Information
| Software       | Version(s)     |
| -------------- | -------------- |
| BusinessEvents |      6.3.0          |
| OS Type?       |    Windows         |
| OS Version?    |    Win 10            |
| Docker         |      24.0.2          |
| Kubernetes     |     NA           |
| Helm           |       NA         |

### What is the expected behavior?
The windows based docker image should have created successfully.

### What is the actual behavior?
The docker image build process is failing for windows.

### Please provide a unit test that demonstrates the bug.
C:\Share\Repo\be-tools\cloud\docker>build_image.bat -i app -a C:\Share\Repo\fdc -s C:\Share\BasicSoftwares\Installers\BE\630\140 -t fdcign:v140
...
...
Step 34/51 : RUN c:\working\be_docker_install.bat
 ---> Running in 91e3c0842917
Extracting ActiveSpaces Legacy 2.4.1
Installing ActiveSpaces Legacy 2.4.1 ...
Extracting BusinessEvents 6.3.0
Installing BusinessEvents 6.3.0 ...
Building annotation indexes..
Copy-Item : Cannot find path 'C:\tibco\be\6.3\bin\_annotations.idx' because it
does not exist.
At line:1 char:1
+ Copy-Item 'c:/tibco/be/6.3/bin/be-engine.tra','c:/tibco/be/6.3\bin\be ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\tibco\be\6.3\bin\_annotation
   s.idx:String) [Copy-Item], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.CopyI
   temCommand
...
...
Step 46/51 : RUN c:\tibco\be\vcredist_install.bat
 ---> Running in cd60c71ae504
The command 'cmd /S /C c:\tibco\be\vcredist_install.bat' returned a non-zero code: 4294967295
ERROR: Docker build failed.

### Please provide log files.
[BE630_Win_docker.txt](https://github.com/TIBCOSoftware/be-tools/files/11914276/BE630_Win_docker.txt)

**Comment by nareshkumarthota** [comment]
@tsaxena18  try with this branch `fix-issue-329`

**Comment by tsaxena18** [comment]
Tested with branch `fix-issue-329` and the windows based docker images are created successfully. Checked with BE installers and installation.
Attached log for the reference.
[Windows-afterfix.txt](https://github.com/TIBCOSoftware/be-tools/files/11999168/Windows-afterfix.txt)
