### ISSUE TITLE
Add ReadMe files for Docker and GV support

### ISSUE THREAD

**Issue by vpatil-tibco** [TIBCOSoftware/be-tools#33]
We need to have Readme files for docker and gv support. End users should find github self sufficient to use. Not need us to redirect them to doc.tibco.com for basic "getting started/usage" stuff.

**Comment by skbasit** [comment]
We now have wiki pages for this.
https://github.com/TIBCOSoftware/be-tools/wiki/Setting%20Up%20the%20Application%20to%20Use%20Global%20Variables%20from%20Consul
