### ISSUE TITLE
Enhance BE TEA Agent container image to include TEA_HOME and its dependencies

### ISSUE THREAD

**Issue by rameshpolishetti** [TIBCOSoftware/be-tools#331]
**Context**
In BE 6.3.0 `teasdk` folder dependency has been removed and added TEA_HOME to `be-engine.tra`. To align to this change, update BE TEA Agent container image logic to - Accept TEA installer zip while building the `teaagent` container image & copy TEA dependencies (jars under teaagent/lib) into the final image.

**Alternatives**
NO

**Has the feature been requested before?**
NA

**If the feature request is approved, would you be willing to submit a PR?**
Yes

**Comment by nareshkumarthota** [comment]
Changes merged into master
