### ISSUE TITLE
Update BE container image optimisation resources

### ISSUE THREAD

**Issue by rameshpolishetti** [TIBCOSoftware/be-tools#338]
**Context**
Revisit & review new dependencies which got added in to BE 6.3.0 to identify optional jars and update optimize.json accordingly.

**Alternatives**
NA

**Has the feature been requested before?**
NA

**If the feature request is approved, would you be willing to submit a PR?**
Yes

**Comment by ykalidin** [comment]
I have validated FraudDetection(Inmemory), Pulsarchannel, Influx, Cassandra, Kafka,  Kafka with Avro and Opentelemetry examples in `chore-optimization` branch.

Below are the observations:
1)"BE_HOME/lib/ext/tpcl/apache/tomcat-embed-core.jar" is in HTTP module.The same is required in kafka.
2)"BE_HOME/lib/ext/tpcl/okhttp*.jar" is in influx module.Its required for opentelemetry.
3)"BE_HOME/lib/ext/tpcl/kotlin-stdlib*.jar" is in influx module.Its required for opentelemetry
4)"BE_HOME/lib/ext/tpcl/okio*.jar" is in influx module.Its required for opentelemetry

The Error messages and details are mentioned in the Optimize sheet.
