### ISSUE TITLE
FTL 6.10.0 is not getting loaded while building docker image

### ISSUE THREAD

**Issue by LakshmiMekala** [TIBCOSoftware/be-tools#339]
### Version Information
| Software       | Version(s)     |
| -------------- | -------------- |
| BusinessEvents |  6.3.0              |
| OS Type?       |    Ubuntu            |
| OS Version?    |     22.04 LTS           |
| Docker         |                |
| Kubernetes     |                |
| Helm           |                |

### What is the expected behavior?
FTL 6.10.0 should be available in BE docker image when FTL installer zip or FTL home set in be-engine.tra
### What is the actual behavior?
Currently When FTL installer zip/FTL home is set in be-engine.tra.., ftl6.10 is not getting added to docker image
### If the bug is confirmed, would you be willing to submit a PR?
Yes / No _(Help can be provided if you need assistance submitting a PR)_

**Comment by ykalidin** [comment]
Verified BE 6.3.0 and FTL 6.10.0 installation with both installers and local installation.Working fine.
