### ISSUE TITLE
RMS docker test failing for BE 6.3.1 using installers 

### ISSUE THREAD

**Issue by LakshmiMekala** [TIBCOSoftware/be-tools#351]
Docker tests were failing when  rms image is built using BE,AS,FTL installers 

Attached logs for reference
[rms-test.log](https://github.com/TIBCOSoftware/be-tools/files/15433205/rms-test.log)

**Comment by nareshkumarthota** [comment]
Due to recent changes in BE 6.3.1 installer( In RMS case eclipse-platform folder is removed). This needs to be handled in scripts.

**Comment by nareshkumarthota** [comment]
Fix available in branch `chore-issues-fix` pls check.

**Comment by ykalidin** [comment]
Working fine.Verified in `feat-java-patch`.
