### ISSUE TITLE
Update JRE version from 11 to 17 for BE 6.3.1

### ISSUE THREAD

**Issue by LakshmiMekala** [TIBCOSoftware/be-tools#352]
Currently we are seeing JRE version 11 for BE 6.3.1 from the docker test logs and they are failing.
Hence Update JRE version from 11 to 17 for BE 6.3.1

**Comment by nareshkumarthota** [comment]
Fix available in branch `chore-issues-fix` pls check.

**Comment by ykalidin** [comment]
Working fine. Verified in feat-java-patch branch.
