### ISSUE TITLE
Container structure tests were running only for last config file

### ISSUE THREAD

**Issue by LakshmiMekala** [TIBCOSoftware/be-tools#353]
Create a docker image with BE,AS,AS4,FTL and at the end check for the container structure tests, test is getting executed only for ftl and tests not running for as, be, as4. 
[contianer-build.log](https://github.com/TIBCOSoftware/be-tools/files/15453321/contianer-build.log)

Same is observed for image built using 6.3

**Comment by nareshkumarthota** [comment]
All the tests are consolidated and they will execute after end of the yaml files. Check each run description you can notice that they are fetched from all the yaml files. The execution behaviour of these tests is purely as per the image `gcr.io/gcp-runtimes/container-structure-test:v1.9.1`
