### ISSUE TITLE
Add support for JRE installer patches to handle CVE's

### ISSUE THREAD

**Issue by vpatil-tibco** [TIBCOSoftware/be-tools#355]
**Context**
Currently if the need is to build image off installers and the JRE version within BE installer needs to be patched due to a CVE or some other reason. Just putting the patch installer along with base BE installer and/or other HF installers does not apply the JRE patch over the base. We should be able to simply put all the installers i.e. base, JRE patches, HF's, etc and the image building should automatically take care of applying all the right patches.

**Alternatives**
Manually install BE and update the JRE with a patch and create the image off that patched installation

**Has the feature been requested before?**
No

**If the feature request is approved, would you be willing to submit a PR?**
Yes

**Comment by ykalidin** [comment]
Verified the following testcases in Linux and Windows-Linux.
1)BE 6.2.1 app image with lower version Jre patch-Patch is not installed
2)BE 6.2.1 app image with higher version Jre patch-Patch is installed
3)BE 6.2.1 app image with higher version Jre patch and 6.2.1 hotfix-Patch and hotfix installed
4)BE 6.2.1 RMS image with lower version Jre patch-Patch is not installed
5)BE 6.2.1 RMS image with higher version Jre patch-Patch is installed
6)BE 6.2.1 Teagent image with lower version Jre patch-Patch is not installed
7)BE 6.2.1 Teagent image with higher version Jre patch-Patch is installed
8)BE 6.2.1 with multiple Jre patches-Appropriate error message seen.
Windows-Windows containers-Jre patch not implemented.

Working fine.
