### ISSUE TITLE
BE 631 Version  ompatability issue with FTL 6.10.0-6.10.2 

### ISSUE THREAD

**Issue by LakshmiMekala** [TIBCOSoftware/be-tools#359]
Current Version BE 6.3.1 is compatable with FTL versions: 6.7.1-7.0.0

When trying to build image with FTL 6.10.0-6.10.2 getting error

ERROR: BE version: [6.3.1] not compatible with FTL version: [6.10.0].

**Comment by LakshmiMekala** [comment]
Also observed openjdk version https://jdk.java.net/java-se-ri/17-MR1 17.0.1 not compatible with BE supported JRE Runtime version

ERROR: OpenJDK Version [17_linux] and BE supported JRE Runtime Version [17] mismatch

**Comment by nareshkumarthota** [comment]
@LakshmiMekala   Pls validate once and close this. changes pushed to master.

**Comment by LakshmiMekala** [comment]
Validated the fix and observed that the build scripts are picking 6.10.0-6.10.2 versions of FTL
