### ISSUE TITLE
Incorrect error message in case of wrong installers are present at installer location while building image

### ISSUE THREAD

**Issue by jgirase** [TIBCOSoftware/be-tools#43]
Command : ./build_app_image.sh -l /home/jgirase/Installers/BE/5.6.1/V59 -a /home/jgirase/work/BE/5.6.1/Consul/561/JMSChannel/ -r jmschannel:561 --gv-providers consul

Installer directory contains AS 2.4.1 linux zip and BE 5.6.1 windows zip
While building image it shows error message as below,
**ERROR: TIBCO BusinessEvents HF is present but TIBCO BusinessEvents Base version is not present in the target directory**.

This error message is not saying that linux installer for base version is missing. Even there is no hotfix present in installer directory as it stated.

**Comment by rameshpolishetti** [comment]
Note: Fix is available in the branch https://github.com/TIBCOSoftware/be-tools/tree/feature-cloud-enhancements

**Comment by jgirase-tibco** [comment]
This is working fine now. For wrong installer , it says following message,
ERROR: TIBCO BusinessEvents Installer is not present in the target directory.

**Comment by rameshpolishetti** [comment]
closing the issue as it is verified successfully.
