### ISSUE TITLE
Keep specific tag version for base OS images instead of using 'latest'.

### ISSUE THREAD

**Issue by tsaxena18** [TIBCOSoftware/be-tools#54]
The docker build script might fails if user already have base OS image tagged as **latest**, (ex, ubuntu:latest) and it is couple of months old. I have encountered such issue and it was not easy to debug. 
So it is better to tag the base OS image with specific version. This fix include updating all the DockerFiles, for ex: 
**FROM ubuntu:latest as intermediate**

**Comment by rameshpolishetti** [comment]
Note: Fix is available in the branch https://github.com/TIBCOSoftware/be-tools/tree/feature-cloud-enhancements

**Comment by tsaxena18** [comment]
Confirmed.
The tag has been fixed to use version instead of using 'latest', as described below from build logs.
**FROM ubuntu:20.10 as intermediate**
Attached build logs for the reference.
[buildApp.txt](https://github.com/TIBCOSoftware/be-tools/files/5050728/buildApp.txt)
