### ISSUE TITLE
Improvements docker image script

### ISSUE THREAD

**Issue by dijadhav** [TIBCOSoftware/be-tools#55]
1) Reduce size of frominstallation docker image
2) Include folders specific to component liek TEA,RMS
3) Create common script for validation of installer

**Comment by nareshkumarthota** [comment]
scripts improved and made available in branch `docker-scripts-improvements`

**Comment by ykalidin** [comment]
Verified as per description.

**Comment by tsaxena18** [comment]
Verified few things as listed below : 
1. Docker image size has been considerably reduced for both Linux and Windows container. For Linux, it is approx. 760mb and for Windows it is 6gb. Same for images built from local installation.

2. The BE application, RMS and TEA images, built from both the methods, have specific folders related to component as described below : 

[apps@beqacentos7 ~]$ docker run -it fdc:610 /bin/bash
root@2bbe0842a4c2:/opt/tibco/be/6.1# ls
bin  lib 

[apps@beqacentos7 ~]$ docker run -it rms:610A /bin/bash
root@96951a3c02f9:/opt/tibco/be/6.1# ls
bin  eclipse-platform  examples  lib  mm  rms  studio

[apps@beqacentos7 ~]$ docker run -it teagent:610 /bin/bash
root@9975ff9413a7:/opt/tibco/be/6.1# ls
bin  lib  mm  teagent

3. The process for building images from installers and from local installations have been clubbed in a single utility, which also include a common script for application, RMS and TEA. Also there is a common unit test which get executed by default for all types of images.

**Comment by rameshpolishetti** [comment]
Thank you @tsaxena18. Closing the issue as it is verified successfully.
