### ISSUE TITLE
runbe.sh script needs update to not keep adding same properties at the end of be-engine.tra every time container runs.

### ISSUE THREAD

**Issue by vijay572** [TIBCOSoftware/be-tools#56]
Issue:
In docker environment (Container created and used to start and stop) on each container restart all GVs and JVM props added again to existing be-engine.tra file.
Caused by this be-engine.tra file grows to 1GB on customer site.

Requred to update runbe.sh script - start BE agent with a backup file copied from orign be-engine.tra file first or overwrite existing settings for each property.

Reproduction:
===============
1.) Create BE application image
2.) Create a docker container from BE image

e.g.:
docker container create "fd:latest"

3.) Check container ID and start/stop container several times

eg:
docker container ls
CONTAINER ID IMAGE COMMAND CREATED STATUS PORTS NAMES
7a8e92fea554 fd:latest "./runbe.sh" 2 hours ago Up About an hour 5555/tcp, 50000-50001/tcp quirky_khayyam

4.)
Start and top container several times:

e.g.:
docker container start 7a8e92fea554
docker container stop 7a8e92fea554
docker container start 7a8e92fea554
docker container stop 7a8e92fea554
docker container start 7a8e92fea554

5.)
Connect to container with terminal (/bin/sh or /bin/bash) and check be-engine.tra file
-> For each restart JVM props added (in sample no GVs configured)

e.g.: Commands and output:

docker exec -it 7a8e92fea554 /bin/sh

cd /opt/tibco/be/5.6/bin
tail be-engine.tra
#
...
Jars that should be skipped by Tomcat server's TLDJarScanner
tomcat.util.scan.DefaultJarScanner.jarsToSkip=xdata.jar,tibrvj.jar
java.property.java.rmi.server.hostname 172.17.0.2
java.extended.properties=-server -Xms1024m -Xmx1024m -Xss2m -javaagent:/opt/tibco/be/5.6/lib/cep-base.jar -XX:MaxMetaspaceSize=256m -XX:+UseParNewGC -XX:+UseConcMarkSweepGC
java.property.java.rmi.server.hostname 172.17.0.2
java.extended.properties=-server -Xms1024m -Xmx1024m -Xss2m -javaagent:/opt/tibco/be/5.6/lib/cep-base.jar -XX:MaxMetaspa java.extended.properties=-server -Xms1024m -Xmx1024m -Xss2m -javaagent:/opt/tibco/be/5.6/lib/cep-base.jar -XX:MaxMetaspaceSize=256m -XX:+UseParNewGC -XX:+UseConcMarkSweepGC
java.property.java.rmi.server.hostname 172.17.0.2
java.extended.properties=-server -Xms1024m -Xmx1024m -Xss2m -javaagent:/opt/tibco/be/5.6/lib/cep-base.jar -XX:MaxMetaspa java.extended.properties=-server -Xms1024m -Xmx1024m -Xss2m -javaagent:/opt/tibco/be/5.6/lib/cep-base.jar -XX:MaxMetasp java.extended.properties=-server -Xms1024m -Xmx1024m -Xss2m -javaagent:/opt/tibco/be/5.6/lib/cep-base.jar -XX:MaxMetasp java.extended.properties=-server -Xms1024m -Xmx1024m -Xss2m -javaagent:/opt/tibco/be/5.6/lib/cep-base.jar -XX:MaxMetaspaceSize=256m -XX:+UseParNewGC -XX:+UseConcMarkSweepGC
java.property.java.rmi.server.hostname 172.17.0.2
java.extended.properties=-server -Xms1024m -Xmx1024m -Xss2m -javaagent:/opt/tibco/be/5.6/lib/cep-base.jar -XX:MaxMetaspa java.extended.properties=-server -Xms1024m -Xmx1024m -Xss2m -javaagent:/opt/tibco/be/5.6/lib/cep-base.jar -XX:MaxMetasp java.extended.properties=-server -Xms1024m -Xmx1024m -Xss2m -javaagent:/opt/tibco/be/5.6/lib/cep-base.jar -XX:MaxMetasp java.extended.properties=-server -Xms1024m -Xmx1024m -Xss2m -javaagent:/opt/tibco/be/5.6/lib/cep-base.jar -XX:MaxMetasp java.extended.properties=-server -Xms1024m -Xmx1024m -Xss2m -javaagent:/opt/tibco/be/5.6/lib/cep-base.jar -XX:MaxMetasp java.extended.properties=-server -Xms1024m -Xmx1024m -Xss2m -javaagent:/opt/tibco/be/5.6/lib/cep-base.jar -XX:MaxMetasp java.extended.properties=-server -Xms1024m -Xmx1024m -Xss2m -javaagent:/opt/tibco/be/5.6/lib/cep-base.jar -XX:MaxMetasp java.extended.properties=-server -Xms1024m -Xmx1024m -Xss2m -javaagent:/opt/tibco/be/5.6/lib/cep-base.jar -XX:MaxMetaspaceSize=256m -XX:+UseParNewGC -XX:+UseConcMarkSweepGC
#

**Comment by skbasit** [comment]
The changes has been merged into master branch since long.
