### ISSUE TITLE
Do we need discoverynode for Shared-Nothing kubernetes deployments

### ISSUE THREAD

**Issue by rameshpolishetti** [TIBCOSoftware/be-tools#66]
It is observed that discoverynode is added for Persistence-None & Shared-All but not for Shared-Nothing. Is there any significance for it?

CC: @vpatil-tibco @CloudDevBe  @vivekshende

**Comment by tsaxena18** [comment]
No. The cache node itself act as discovery node in any case (None, Shared All, Shared Nothing). We may have included an extra node for discovery in some folder but that is not mandatory in general. It is just to showcase the behavior/importance of discovery node by running an extra node explicitly. You can, if you want, include a separate discovery node in Shared Nothing too but that's optional.

**Comment by dijadhav** [comment]
Tammay is correct.Whatever we have written  for these use cases are different ways to create discovery. We have provided examples its upto user how they want to do.

**Comment by vpatil-tibco** [comment]
@rameshpolishetti - Let the discovery node for existing scripts. But let's not bring it to helm.
