### ISSUE TITLE
Be application throwing waiting for space error in k8s deployments

### ISSUE THREAD

**Issue by LakshmiMekala** [TIBCOSoftware/be-tools#67]
discovery and inference pods are giving waiting for space error in k8s cache mode deployments.

Observed discovery=[tibpgm] in individual pod logs.
Error is in generating docker image.

Cc: @vpatil-tibco @vivekshende

**Comment by dijadhav** [comment]
Please add new line "\n" in Dockerfile before the line (line # 56) we write AS ur in TRA . Also update ubuntu from latest to 16.04 or 18.04

**Comment by vpatil-tibco** [comment]
@rameshpolishetti mentioned, this has nothing to do with ubuntu update. Seems it was a miss.
@LakshmiMekala Can you put a line feed fix on this.

**Comment by rameshpolishetti** [comment]
Note: Fix is available in the branch https://github.com/TIBCOSoftware/be-tools/tree/feature-cloud-enhancements

**Comment by LakshmiMekala** [comment]
Closing as the fix is available in master
