### ISSUE TITLE
Windows docker script build_app_image.bat not work with more than 4 parameters

### ISSUE THREAD

**Issue by skbasit** [TIBCOSoftware/be-tools#70]

**Comment by kagrawal-git** [comment]
Added shift command.

**Comment by nareshkumarthota** [comment]
Fix available in branch `docker-scripts-improvements`

**Comment by ykalidin** [comment]
Consolidated script uses build_image.bat. Script is working for more than 4 arguments as expected.
Verified in `docker-scripts-improvements` branch.

**Comment by tsaxena18** [comment]
Verified with more than 4 parameters and it went fine for windows script.
Attached build log file for the reference. 
[docker-build.txt](https://github.com/TIBCOSoftware/be-tools/files/5709108/docker-build.txt)

**Comment by rameshpolishetti** [comment]
Thank you @tsaxena18. Closing the issue as it is verified successfully.
