### ISSUE TITLE
docker scripts - /gvproviders/consul/setup.sh (wget package not installed, so consul binaries not loaded)

### ISSUE THREAD

**Issue by vijay572** [TIBCOSoftware/be-tools#72]
Issue:
Consul binaries not loaded when build the docker image with latest docker build scripts.
(https://github.com/TIBCOSoftware/be-tools/tree/v1.0).

That is related to a missing command when load the wget package in ubuntu image.
Without wget installed, it's not possible to load the binaries so it failed to load GVs from consul (script error reported on startup of the docker container when execute gvproviders/consul/run.sh (line 33 binaries missign).

To fix the issue update docker script /gvproviders/consul/setup.sh and add "apt-get update" gefore load the wget package.

Content:
=================================================================
#!/bin/bash

#

Copyright (c) 2019. TIBCO Software Inc.
This file is subject to the license terms contained in the license file that is distributed with this file.
#
echo "Setting up consul gv provider.."

cd /home/tibco/be/gvproviders/consul

Support: required to install wget package correctly
apt-get update
apt-get install -y wget
Download jq.
wget "https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64"
mv jq-linux64 jq
chmod +x jq
Download consul cli and extract it.
wget "https://releases.hashicorp.com/consul/1.6.1/consul_1.6.1_linux_amd64.zip"
unzip consul_1.6.1_linux_amd64.zip
rm consul_1.6.1_linux_amd64.zip
===========================================================================
Note:
As a workaround for now, I suggested customer to download the files, unzip jq-linux64, rename the binary to "jq" and copy both files to gvproviders\consul before build the image.

**Comment by vijay572** [comment]
@vivekshende @skbasit created this issue to track internal JIRA created by Ulf

**Comment by nareshkumarthota** [comment]
gvproviders framework is restructured. This issue is considered and changes made available in branch `docker-scripts-improvements`

**Comment by ykalidin** [comment]
Working as expected. Verified with the branch `docker-scripts-improvements`.

**Comment by jgirase** [comment]
Image is built successfully with consul gv provider.
[consul_image_docker.log](https://github.com/TIBCOSoftware/be-tools/files/5715724/consul_image_docker.log)

Find attached logs for reference

**Comment by rameshpolishetti** [comment]
Thank you @jgirase. Closing the issue as it is verified successfully.
