### ISSUE TITLE
Reduce the size of windows based docker image

### ISSUE THREAD

**Issue by vshende-tibco** [TIBCOSoftware/be-tools#83]
The BE docker image built for windows container is of size 12 GB approx. which is large considering that we are building it from frominstall which is used for creating images of less size. The application image will take 1 GB more so there should be a way to create these images of less size.

Also reduce the engine startup time as it is taking longer time as compared with linux containers.
Attaching build image log for the reference.

(Migrated issue https://jira.tibco.com/browse/BE-26668 from Jira to GitHub)

**Comment by nareshkumarthota** [comment]
From the logs, I could see that out of 12gb window base image (mcr.microsoft.com/windows/servercore   ltsc2016 2b98a92e72d0) contributing 11 gb + be artifacts 1 gb

I also tried using windows nano container (mcr.microsoft.com/windows/nanoserver 1903 8b8ec38e0f40 - who's size is of 300MB) as base image to reduce BE app container size. Below are the observations:

1.  FTL installation is failing as .net framework is not available in nano container
2.  There are images like nano+.net who's size ~4.5 GB, which is similar to windows servercore

**Comment by vpatil-tibco** [comment]
@nareshkumarthota if nano+.net ends up being of same size as the latest windows servercore (2019) i.e. ~ 4.7 GB. Then i don't see a point customizing this image. Latest servercore should do.

It's be good to check if the startup time is being spent in our scripts or its more of the Windows issue.

**Comment by nareshkumarthota** [comment]
windows docker size and startup time improvements are available in branch `docker-scripts-improvements`

**Comment by ykalidin** [comment]
Latest windows image size is reduced. Runtime performance improved. Working as expected.

**Comment by tsaxena18** [comment]
Verified docker image size, created from installers as well as from BE installations and they have been reduced considerably as shown below : 
C:\Share\be-tools-docker-scripts-improvements\cloud\docker>docker images
REPOSITORY                             TAG        IMAGE ID       CREATED          SIZE
fdc                                    v64        963da91b626c   55 minutes ago   6.27GB
fdc                                    v64fi      9161107bbde3   3 hours ago      6.31GB
fdci                                   v64fi      93865dbc00b2   3 hours ago      6.31GB
fdci                                   v64        e3156472c95d   4 hours ago      6.27GB
mcr.microsoft.com/windows/servercore   ltsc2019   c0773f9ce353   13 days ago      5.12GB

**Comment by rameshpolishetti** [comment]
Closing the issue as it is verified successfully.
