### ISSUE TITLE
The docker build script for TEA is failing.

### ISSUE THREAD

**Issue by tsaxena18** [TIBCOSoftware/be-tools#86]
The docker build scripts of app and RMS are working fine but the script for TEA is failing for the same set of installers.
I have used AS 2.4.1 and BE 5.6.1 installers [AS + BE Enterprise + Process + Views]. All the installers are kept in same folder.
Attached log for the failed build script for TEA.
  
[buildTEAgent.txt](https://github.com/TIBCOSoftware/be-tools/files/4904757/buildTEAgent.txt)

**Comment by nareshkumarthota** [comment]
Root cause for the issue - apt-get upgrade python-pip  is failing in the "ubuntu:latest". Now latest is 20.04.
using ubuntu:18.04 as base version should fix the issue.

**Comment by vpatil-tibco** [comment]
@nareshkumarthota as discussed the best option would be to fix the command. Since even with our Helm branch, we are pinning it to 20.x.

**Comment by nareshkumarthota** [comment]
Both Ubuntu version and python commands updated. Fix is available in branch `fix-issue-86`. will merge into master along with helm branch.

**Comment by nareshkumarthota** [comment]
be-hf fix with tea scripts also updated in branch `fix-issue-86`.
