### ISSUE TITLE
Parameters in values.yaml file under Helm should be same as in CDD for consistency.

### ISSUE THREAD

**Issue by tsaxena18** [TIBCOSoftware/be-tools#98]
The initial BE parameters such as unclustered, inmemory, store, cache, sharedNothing, etc are not consistent with the CDD. They should be equal in upper/lower case, i.e, the string should be same as seen in CDD.

**Comment by vpatil-tibco** [comment]
Not really mandatory, in fact its not a good practice to have field/variables/parameters on cli have spaces, be case sensitive, etc. So long as the names are self explanatory and have appropriate doc/help details explaining.

The only change i feel we can make is change "sharedNothing" to "sharednothing". Keep all options lower case.

**Comment by LakshmiMekala** [comment]
Fix is available in branch [fix-issue-98](https://github.com/TIBCOSoftware/be-tools/tree/fix-issue-98)
